### ISSUE TITLE
group(sort) candidates by 'info' before rendering

### ISSUE THREAD

**Issue by idanko** [prabirshrestha/asyncomplete.vim#102]
I use [asyncomplete-gocode.vim](https://github.com/prabirshrestha/asyncomplete-gocode.vim) and it has the kind prefix (func|var|const|...) on each pop-up candidates. It groups by that kind in unsorted way and issue comes when having them a lot:

<img width="925" alt="screen shot 2019-01-29 at 11 20 40 pm" src="https://user-images.githubusercontent.com/8293386/51941141-86c12580-241c-11e9-9387-fa00ca225cf6.png">

It would be better having a sort functionality, Imho

**Comment by prabirshrestha** [comment]
While this doens't answer your question. I would suggest giving language server a try. https://github.com/prabirshrestha/vim-lsp.
https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Go

Beside code completion you get other features such as gotodef, rename and so on.

**Comment by idanko** [comment]
The language server for Go is based on the [go-langserver](https://github.com/sourcegraph/go-langserver) project where is asyncomplete-golang is based on the gocode binary (https://github.com/mdempsky/gocode for instance). Both of them are different with different bugs and features.

**Comment by prabirshrestha** [comment]
In v2 I do plan to allow custom filtering function. User should be able to write customer filtering functions there.

**Comment by prabirshrestha** [comment]
Please try the v2 branch. It now support custom preprocessor using `g:asyncomplete_preprocessor`.
You should now be able to do anything you want in your function.

https://github.com/prabirshrestha/asyncomplete.vim/blob/1eacfe20b68d48f0168b83b3df0e008054a15ba3/doc/asyncomplete.txt#L55-L86
