### ISSUE TITLE
Flickering when typing while pumvisible and smart_completion on

### ISSUE THREAD

**Issue by jsit** [prabirshrestha/asyncomplete.vim#107]
@roxma's vimrc [here](https://github.com/vim/vim/issues/1713#issuecomment-401518386) doesn't flicker

Your vimrc [here](https://github.com/vim/vim/issues/1713#issue-230132610) still *does* flicker, even with vim/vim#1713

What is the significant difference between these two? Can asyncomplete.vim be updated with something similar to prevent flickering?

**Comment by jsit** [comment]
Closing in favor of #108.

**Comment by roxma** [comment]
> What is the significant difference between these two?

Timer based auto completion check cannot avoid flicker with current set of vim api. As pointed out by brammool 

https://github.com/vim/vim/issues/1713#issuecomment-455795951

> The example using a timer will always flicker, because the popup menu is removed when a character is typed, and it is opened again a bit later when the timer triggers and calls complete(). Vim cannot predict if or when the popup menu will be shown again.
