### ISSUE TITLE
Don't run complete() if list of candidates hasn't changed

### ISSUE THREAD

**Issue by jsit** [prabirshrestha/asyncomplete.vim#109]
The popup menu is updated (at least) once every time text is inserted, even if the list of candidates hasn't changed. This shouldn't happen; the menu should only update if the list of candidates is different.

May be a solution to #108.

**Comment by prabirshrestha** [comment]
This one will be a bit tricking once we have custom filtering func. but please give v2 a try.

**Comment by prabirshrestha** [comment]
v2 now include preprocessor which changes the candidates. Let me know if this is still the case.
