### ISSUE TITLE
Matches are normalized too frequently

### ISSUE THREAD

**Issue by jsit** [prabirshrestha/asyncomplete.vim#111]
Matches are "normalized" every time `python_refresh_completions` runs, which is every keystroke on insert mode. This can means it runs hundreds of times per keystroke. Shouldn't this match list only need to be normalized once for each source?

https://github.com/prabirshrestha/asyncomplete.vim/blob/2ffa939cb7cd424b595b5ea25470a621767436b3/autoload/asyncomplete.vim#L433-L441

**Comment by prabirshrestha** [comment]
Please try v2 branch. It is now only normalized during `#complete()` call. I also went further to look at the first item of the curmatches and only normalize if it isn't a dict.

**Comment by prabirshrestha** [comment]
Fixed in v2.
