### ISSUE TITLE
python_refresh_completions() is run for every source during remote_refresh()

### ISSUE THREAD

**Issue by jsit** [prabirshrestha/asyncomplete.vim#112]
This should only have to run once per `remote_refresh()`, not once for every source; nothing unique to any source is passed to this function, so it could just come after the loop.

https://github.com/prabirshrestha/asyncomplete.vim/blob/2ffa939cb7cd424b595b5ea25470a621767436b3/autoload/asyncomplete.vim#L284-L286

**Comment by prabirshrestha** [comment]
Can you try v2 branch. We should still fix it there.

**Comment by prabirshrestha** [comment]
Shouldn't be happening in v2.
