### ISSUE TITLE
Does asyncomplete.vim require async.vim?

### ISSUE THREAD

**Issue by jsit** [prabirshrestha/asyncomplete.vim#114]
It's not clear from the README whether asyncomplete.vim requires async.vim.

**Comment by prabirshrestha** [comment]
async.vim is not required. It may be required by sources.

async.vim is a single file that can be checked in to its own repro. Something like how minpac does. https://github.com/k-takata/minpac/blob/ce8ab7267a4071e8b3081d10861b9b8c29238b07/autoload/minpac/job.vim
I have to write scripts to make it easy to do this.
