### ISSUE TITLE
Allow user to set delay before menu pops up

### ISSUE THREAD

**Issue by jsit** [prabirshrestha/asyncomplete.vim#115]
It would be useful if users could set an optional delay that would prevent the menu from popping up until they stopped typing for a specified number of milliseconds; if typing quickly enough, the menu wouldn't pop up until you paused typing briefly. This would also help prevent thrashing/flickering, as the menu would be called less often.

I thought this is what `let g:asyncomplete_completion_delay`, but that doesn't seem to be the case.

**Comment by prabirshrestha** [comment]
Would this work? https://github.com/prabirshrestha/asyncomplete.vim/blob/e52e70c72ceebff5e8a9c8cdeb50f9bebcbdd9db/autoload/asyncomplete.vim#L304 If that is the case we might need to add it as a config that can be set by user.

**Comment by jsit** [comment]
Looks like this works, yeah. I added a new PR, #121.

**Comment by prabirshrestha** [comment]
Available in v2 by https://github.com/prabirshrestha/asyncomplete.vim/pull/121
