### ISSUE TITLE
<CR> cannot be inserted when a popup window opens

### ISSUE THREAD

**Issue by ichitera** [prabirshrestha/asyncomplete.vim#117]
When a popup appears, we cannot go to the next line by pressing <kbd>Enter</kbd>.

This is the screencast to explain this issue. In this screencast, I cannot the next line from line 6.

![screencast for this issue](https://user-images.githubusercontent.com/31098747/52389393-a5878200-2ad6-11e9-9a19-f118b9e750b0.gif)

I used the following vimrc:
```VimL
set nocompatible hidden laststatus=2
language C
set number

if !filereadable('plug.vim')
  silent !curl --insecure -fLo plug.vim
    \  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif
source plug.vim

call plug#begin('plugged')
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'
call plug#end()

let g:lsp_log_verbose = 1
let g:lsp_log_file = './vim-lsp.log'
let g:asyncomplete_log_file = './asyncomplete.log'
imap <c-space> <Plug>(asyncomplete_force_refresh)

au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
      \ 'name': 'buffer',
      \ 'whitelist': ['*'],
      \ 'priority': 0,
      \ 'completor': function('asyncomplete#sources#buffer#completor'),
      \ }))
```

### Environment

- Windows 10 64bit
- Vim: 8.1.877
- async.vim: [4bde72e](https://github.com/prabirshrestha/async.vim/tree/4bde72e27eff8f2bb9821b092eb6e9df51219082)
- asyncomplete.vim: 2ffa939
- asyncomplete-buffer.vim: [9cea331](https://github.com/prabirshrestha/asyncomplete-buffer.vim/tree/9cea33127be464b53eb779646a49104d1191d3eb)

This issue is maybe releated to: #85

**Comment by prabirshrestha** [comment]
Can you try if you see this bug in v2 branch? Still at an early phase of v2.

**Comment by ichitera** [comment]
Thank you for the information of the v2 branch.

I tried 1eacfe2 in the v2 branch, but I still saw this issue. In the v2 branch, I could see that the popup menu closed for a moment.

**08437a0 (master branch):**
![master](https://user-images.githubusercontent.com/31098747/53708108-36067780-3e75-11e9-99bc-971448e88e0b.gif)
(The popup menu looks as if it were left open.)

**1eacfe2 (v2 branch):**
![v2](https://user-images.githubusercontent.com/31098747/53708051-f2137280-3e74-11e9-9060-893d0c057181.gif)
(The popup menu closes for a moment after I pressed <kbd>Enter</kbd>.)

I would like to try the v2 branch again after the branch is updated.

**Comment by prabirshrestha** [comment]
Can you try this PR and add mapping for `<CR>`. https://github.com/prabirshrestha/asyncomplete.vim/pull/98

Let me know if that works. Might need to port that to v2 branch.

**Comment by ichitera** [comment]
I tried #98 and  confirmed that this issue was solved.

I mapped `<CR>`  as follows:
```VimL
inoremap <expr> <CR> pumvisible() ? asyncomplete#close_popup() . "\<CR>" : "\<CR>"
```

This is the screencast of a trial of #98:
![a trial of #98](https://user-images.githubusercontent.com/31098747/53710476-c5655800-3e80-11e9-8f1e-d091c8a462f0.gif)
(I could insert `<CR>` when the popup menu was open.)

The below is whole vimrc:
```VimL
set hidden laststatus=2
language C
set number

if !filereadable('plug.vim')
  silent !curl --insecure -fLo plug.vim
    \  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source plug.vim

call plug#begin('plugged')
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'
call plug#end()

let g:lsp_log_verbose = 1
let g:lsp_log_file = './vim-lsp.log'
let g:asyncomplete_log_file = './asyncomplete.log'
imap <c-space> <Plug>(asyncomplete_force_refresh)
inoremap <expr> <CR> pumvisible() ? asyncomplete#close_popup() . "\<CR>" : "\<CR>"

au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
      \ 'name': 'buffer',
      \ 'whitelist': ['*'],
      \ 'priority': 0,
      \ 'completor': function('asyncomplete#sources#buffer#completor'),
      \ }))
```

**Comment by prabirshrestha** [comment]
That is great. I would like to depreact v1 soon so will wait for the PR for v2 branch instead. Feel free to send if you would like too.

**Comment by electric-ladyland** [comment]
Is there a workaround for this before v2 is officially released? Seems asyncomplete#close_popup() is removed.

**Comment by prabirshrestha** [comment]
https://github.com/prabirshrestha/asyncomplete.vim/pull/134 is merged to master. Please try the latest master. Docs contains how to use it.

**Comment by ichitera** [comment]
The PR #134 works fine. Thank you, @prabirshrestha and @ishitaku5522
