### ISSUE TITLE
init_lua() fails for file paths containing special characters

### ISSUE THREAD

**Issue by rogersai** [prabirshrestha/asyncomplete.vim#118]
I have an environment set up where my Neovim installation lives inside a directory with a "#" in the path. This will cause the luafile command in init_lua() to fail when it tries to expand '#' to the alternate file name.

I was able to get it working using the shellescape() function, then trimming the surrounding double quotes that shellescape() produces.

My version of the function is below, but there may be a more elegant solution.

```
function! s:init_lua() abort
    exec 'lua asyncomplete_folder="' . s:asyncomplete_folder . '"'
    let s:lua_file = shellescape(s:asyncomplete_folder . '/lua/asyncomplete.lua', 1)
    exec 'luafile ' . s:lua_file[1:len(s:lua_file)-2]
endfunction
```

**Comment by prabirshrestha** [comment]
Feel free to send a PR.

In v2 branch we are going to remove lua support and one can write a custom filter function.

**Comment by prabirshrestha** [comment]
v2 branch has been merged and it no longer support the smart completion. You will need to add custom preprocessor.
