### ISSUE TITLE
Source for filesystem path completion

### ISSUE THREAD

**Issue by andreypopp** [prabirshrestha/asyncomplete.vim#12]
It would nice to have a source which completes filesystem paths.

It's even better if such source could complete paths relative to the current buffer rather then `cwd` (this is how Vim's built-in fs path completion works I believe).

**Comment by prabirshrestha** [comment]
This is on my todo list. For now you can use vim file completion using `<c-x><c-f>` with asyncomplete.

**Comment by prabirshrestha** [comment]
created an empty repository for now https://github.com/prabirshrestha/asyncomplete-file.vim

**Comment by roxma** [comment]
I just noticed vim's `path` option recently, it's usefule to integrate it into the completion too.

NCM currently uses these base directories for path completion:

- directory of current buffer `expand('%:p')`
- directory of current working directory `getpwd()`
- root directory, which is `/` on linux system.
- directories listed in `path` option

**Comment by prabirshrestha** [comment]
Given that we now have LSP support for both vim and neovim with autocomplete that works for asyncomplete, NCM and deoplete might be better to write a lang server instead. This way one could write in any language they want and actually be used by in any plugin. Here is a language server I wrote for typescript https://github.com/prabirshrestha/typescript-language-server. It is very easy to write one.

**Comment by cvlmtg** [comment]
Hi, i've hacked together a file completion source. I'm a total vimscript noob, so this code is probably inefficient or event totally wrong (and it's not async), but it seems to do its work, so I'm sharing it here with the hope it might be useful to someone else, until a proper plugin is written by someone more experienced 😃 

the path is always relative to the file being edited and there are no configurations or other tricks (like maybe using `git ls-files` in a git repo) but this is left as an exercise to the reader


```vim
function! s:filename_map(prefix, file) abort
  let l:abbr = fnamemodify(a:file, ':t')
  let l:word = a:prefix . l:abbr

  return {
        \ 'menu': '[path]',
        \ 'word': l:word,
        \ 'abbr': l:abbr,
        \ 'icase': 1,
        \ 'dup': 0
        \ }
endfunction

function! s:filename_completor(opt, ctx) abort
  let l:bufnr = a:ctx['bufnr']
  let l:typed = a:ctx['typed']
  let l:col   = a:ctx['col']

  let l:kw    = matchstr(l:typed, '<\@<!\.\{0,2}/.*$')
  let l:kwlen = len(l:kw)

  if l:kwlen < 1
    return
  endif

  if l:kw !~ '^/'
    let l:cwd = expand('#' . l:bufnr . ':p:h') . '/' . l:kw
  else
    let l:cwd = l:kw
  endif

  let l:glob = fnamemodify(l:cwd, ':t') . '*'
  let l:cwd  = fnamemodify(l:cwd, ':p:h')
  let l:pre  = fnamemodify(l:kw, ':h')

  if l:pre !~ '/$'
    let l:pre = l:pre . '/'
  endif

  let l:cwdlen   = strlen(l:cwd)
  let l:startcol = l:col - l:kwlen
  let l:files    = split(globpath(l:cwd, l:glob), '\n')
  let l:matches  = map(l:files, {key, val -> s:filename_map(l:pre, val)})

  call asyncomplete#complete(a:opt['name'], a:ctx, l:startcol, l:matches)
endfunction

call asyncomplete#register_source({
      \ 'name': 'filenam',
      \ 'whitelist': ['*'],
      \ 'priority': 10,
      \ 'completor': function('s:filename_completor'),
      \ })
```

**Comment by prabirshrestha** [comment]
@cvlmtg could you send a PR to https://github.com/prabirshrestha/asyncomplete-file.vim?

**Comment by cvlmtg** [comment]
@prabirshrestha if you think this code is good enough I will

**Comment by cvlmtg** [comment]
(btw the fork button is disabled. maybe you should push a commit first)

**Comment by prabirshrestha** [comment]
@cvlmtg send a PR and we can iterate there. Easier to comment in a PR. I pushed the initial commit you should be able to fork now.

**Comment by prabirshrestha** [comment]
@cvlmtg Thanks a lot for the PR.

Closing this issue, for the any related file asyncompletions we can now use https://github.com/prabirshrestha/asyncomplete-file.vim to continue discussion there.
