### ISSUE TITLE
Error when type ~/

### ISSUE THREAD

**Issue by tuyenpm9** [prabirshrestha/asyncomplete.vim#125]
Steps:
1. vi new_buffer
2. insert ~/
3. vim echo error:

> Error detected while processing function <SNR>69_complete_timeout[6]..<SNR>69_python_cm_complete_timeout[2]..<SNR>69_python_refresh_completions[51]..<SNR>69_filter_completion_items

this timeout function belong to asyncomplete.vim line 319 and 516.

> Internal error: estimated max number of states insufficient: 0

> E33: No previous substitute regular expression

**Comment by prabirshrestha** [comment]
Can you try the v2 branch.

**Comment by tuyenpm9** [comment]
I can confirm that v2 work well.

**Comment by prabirshrestha** [comment]
Great. Please continue using v2. Plan is to merge it to master in a week.
