### ISSUE TITLE
completion inserts extra information

### ISSUE THREAD

**Issue by sbromberger** [prabirshrestha/asyncomplete.vim#128]
With the go language server (gopls), the completion will insert the entire function signature, which is almost never what is wanted.

The first screenshot shows the autocompletion option:

![IMG_0051](https://user-images.githubusercontent.com/941359/54629183-3f2a4380-4a34-11e9-9945-6ecf1b4c91a7.png)

The second screenshot shows me selecting the last option:

![IMG_0052](https://user-images.githubusercontent.com/941359/54629203-4a7d6f00-4a34-11e9-9f5a-2276e4ae699d.png)

The final screenshot shows what gets inserted. Note that `format string, a ...interface{}` is not needed and is actually harmful because it results in errors and forces the user to erase.

![IMG_0053](https://user-images.githubusercontent.com/941359/54629241-641eb680-4a34-11e9-966e-adae42c36f14.png)

Am I missing a configuration option here? Thank you.

**Comment by sbromberger** [comment]
This looks like the go equivalent of 
https://github.com/prabirshrestha/vim-lsp/issues/328

**Comment by prabirshrestha** [comment]
Let us use this to track as there has been ongoing discussions already on it. https://github.com/prabirshrestha/vim-lsp/issues/328#issuecomment-492646814
