### ISSUE TITLE
Support enabling/disabling completion

### ISSUE THREAD

**Issue by pwntester** [prabirshrestha/asyncomplete.vim#129]
Hi,

I would like to disable autocomplete for large files. is there any function I can call to disable it?

Thanks

**Comment by prabirshrestha** [comment]
Can you provide an example on what you are trying to accomplish? That way it will allow me to figure out how to implement it. Certain sources does implement their own threshold. https://github.com/prabirshrestha/asyncomplete-tags.vim

**Comment by maamo888** [comment]
Hi, @pwntester 

**Enable**

```vim
:let b:asyncomplete_enable=1
```

**Disable**

```vim
:let b:asyncomplete_enable=0
```

**Comment by pwntester** [comment]
Thanks @maamo888 that worked 👍 

@prabirshrestha  I was trying to disable autocompletion on large buffers. with deoplete I had something like:

```
    autocmd BufEnter * nested if getfsize(@%) < 1000000 | call deoplete#enable() | endif
```
