### ISSUE TITLE
add a minimal vimrc so users can play asyncomplete with minimal effort

### ISSUE THREAD

**Issue by prabirshrestha** [prabirshrestha/asyncomplete.vim#13]

**Comment by andreypopp** [comment]
I also wonder if we could ship some `<Plug>` mappings as this
```
inoremap <silent><expr> <TAB>
  \ pumvisible() ? "\<C-n>" :
  \ <SID>check_back_space() ? "\<TAB>" :
  \ asyncomplete#force_refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
inoremap <expr> <cr> pumvisible() ? "\<C-n>\<cr>" : "\<cr>"
```
Look a bit verbose for such a common setup.

**Comment by roxma** [comment]
Some plugin has `let g:foo_default_mappings_enable = 1` (I don't remember which one). Disabled by default. This  is a way of  shipping some common mappings.

IMO those tab mappings is still simple.  A user should understand the mapping before adopting it. There will be cases in which  you need to fix incompatible mappings between plugins.

**Comment by prabirshrestha** [comment]
I love the idea of a the variable to enable default mapping `let g:asyncomplete_use_default_mappings = 1` which is disabled by default.

Gina is one of them that supports it via `g:gina#command#blame#use_default_mappings`

**Comment by prabirshrestha** [comment]
decided not to implement it for now. vim-lsp contains a minimal vimrc file https://github.com/prabirshrestha/vim-lsp/blob/b33a69e2b13b94c97a96f4e45833b7fd8d282916/minimal.vimrc
