### ISSUE TITLE
Smart (fuzzy) completion

### ISSUE THREAD

**Issue by jsit** [prabirshrestha/asyncomplete.vim#137]
It used to be that `let g:asyncomplete_smart_completion = 0` would allow "fuzzy" completion, but this appears not to be the case anymore. Can we please get this back?

**Comment by prabirshrestha** [comment]
There are no plans to bring smart completion in the core. This can be done in user mode. 
Here is an example of a pre processor. I haven’t tried it yet. https://github.com/machakann/asyncomplete-ezfilter.vim
Also with support for native async in vim such as webworkers the possibility to make smart completion really good becomes very easy. https://github.com/bobpepin/vim/issues/1

**Comment by izemmouri** [comment]
Well, I tried it, and got something like this:

function! FuzzyFilter(item,ctx)
	let l:filter = '--filter ' . a:ctx
	let l:itemlist = []
	call add(l:itemlist, a:item)
	return fzf#run({'options': l:filter, 'source': l:itemlist}) != []
endfunction

let g:asyncomplete_preprocessor =
	\ [function('asyncomplete#preprocessor#ezfilter#filter')]

let g:asyncomplete#preprocessor#ezfilter#config = {}

let g:asyncomplete#preprocessor#ezfilter#config['*'] =
	\ {ctx, items -> filter(items, 'FuzzyFilter(v:val.word, ctx.base)')}

but as this runs synchronously, it's very unpleasant.

**Comment by jsit** [comment]
@izemmouri Yeah, I'm trying this too -- I'd love to be able to use fzf to look for matches; is there a way to run `fzf#run` without leaving the main Vim view?

**Comment by prabirshrestha** [comment]
@jsit You might want to try this. https://github.com/tsufeki/asyncomplete-fuzzy-match It actually uses skim which is fzf alternative written in rust but is also exposed as a library which the plugin uses and avoid spinning new window inside vim. You could do something similar for fzf but one would need to write code. I personally haven't tried it but by looking at the code it does seem possible. Another option you could do is create a plugin similar to that but use the language you are comfortable in. There are already bunch of fuzzy libs out there that you could use.

**Comment by izemmouri** [comment]
I doubt it matters at all whether it's fzf or something else, as long as it's convenient, you know. The point is to select a match through fuzzy matching. If this asycomplete-fuzzy-match can do it, I'd be happy to use it. Gonna give it a try.

**Comment by prabirshrestha** [comment]
If you want you can also try to easily port the old fuzzy match to use preprocessor. Should be fairly simple. https://github.com/prabirshrestha/asyncomplete.vim/tree/v1.7

**Comment by jsit** [comment]
@izemmouri I feel like I'm kind of close with something like this:

```vim
function FuzzyFilter(item, ctx)
  return system('fzf --filter ' . a:ctx, a:item) != ''
endfunction

let g:asyncomplete#preprocessor#ezfilter#config.neosnippet =
  \ {ctx, items -> filter(items, 'FuzzyFilter(v:val.word, ctx.base)')}
```

But there's still some stuttering. Can't figure out how to make this run asynchronously.

**Comment by prabirshrestha** [comment]
`system` is sync. to make it run async you need to use jobs apis. You can use asyn.vim or this wrapper https://github.com/prabirshrestha/asyncomplete-tags.vim/blob/c3c575a62a34661134e9e9427fdcc46dc50a5069/autoload/asyncomplete/sources/tags.vim#L121-L187

**Comment by izemmouri** [comment]
I did try https://github.com/tsufeki/asyncomplete-fuzzy-match and it seems to work well, except for it might be a bit slow sometimes (I can't tell if it's the fuzzy-matching or the number of sources that makes it hangy though). But that does it (it's likely it'll be better than filtering every single match through fzf, although I don't know for sure). Let us know if something works better for you.

**Comment by prabirshrestha** [comment]
This is now supported in vim via `matchfuzzypos`. Make sure to update to vim that has it.

https://github.com/prabirshrestha/asyncomplete.vim/pull/246

**Comment by FuDesign2008** [comment]
I open https://github.com/prabirshrestha/asyncomplete.vim/issues/279 for smart fuzzy completion.

**Comment by FuDesign2008** [comment]
I create https://github.com/FuDesign2008/asyncomplete-smart-fuzzy.vim to add smart-case filter.

<table>
<tbody>
<tr>
  <th>matches</th>
  <th>foo</th>
  <th>fOo</th>
</tr>
<tr>
  <th>foo</th>
  <td>✔️</td>
  <td>❌</td>
</tr>
<tr>
  <th>fOo</th>
  <td>✔️</td>
  <td>✔️</td>
</tr>
</tbody>
</table>
