### ISSUE TITLE
priority settings not mentioned anywhere in source/doc

### ISSUE THREAD

**Issue by mkoura** [prabirshrestha/asyncomplete.vim#139]
The "priority" settings is mention in an example in README, however there's no mention of it neither in the documentation nor in the source code.

**Comment by prabirshrestha** [comment]
`priority` has been removed in v2. I updated README to reflect it. You can create your own preprocessor to easily support priority.

Here are some you can try.
https://github.com/tsufeki/asyncomplete-fuzzy-match
https://github.com/machakann/asyncomplete-ezfilter.vim
