### ISSUE TITLE
Autocompletion always overwrites vim's completeopt setting

### ISSUE THREAD

**Issue by xulongwu4** [prabirshrestha/asyncomplete.vim#140]
I used `pyls` with `vim-lsp` and `asyncomplete` for autocomplete python code. This is how it usually looks like.
![Screenshot from 2019-05-27 09:47:15](https://user-images.githubusercontent.com/16892446/58424017-7c2e3a00-8064-11e9-927a-e0d0d6cb7b42.png)

I hope to see the docstring of the selected function as well. I checked the value of `completeopt` and it is set to
`completeopt=menuone,noinsert,noselect`.

Then I did `:set completeopt+=preview` and checking `completeopt` again gives me
`completeopt=menuone,noinsert,noselect,preview`. This is expected result.

However, the autocompletion still does not show a docstring in a preview window. After the autocompletion, I checked the value of `completeopt` again and it gives me
`completeopt=menuone,noinsert,noselect`.

So the addition of `preview` does not persist during the autocompletion. Is this a bug or am I not doing it correctly?

**Comment by prabirshrestha** [comment]
Refer to doc on g:asyncomplete_auto_completeopt

**Comment by xulongwu4** [comment]
Thanks. That solves my problem.
