### ISSUE TITLE
On Neovim, Completion Menu Flickers and Closes under Certain Scenarios

### ISSUE THREAD

**Issue by simeir** [prabirshrestha/asyncomplete.vim#141]
Firstly, thank you for this awesome project!

Neovim version: v0.4.0-837-ge0348c610. This version has `complete_info()`.

The problem happens when multiple sources are used. I tested using `asyncomplete-lsp` and `asyncomplete-file` with default settings. After a trigger character which is in refresh pattern is inserted and input stops, the completion menu would flicker and close. For example, when writing python code with `pyls`, this happens after a `.` is inserted and input stops.

I looked into the code and found that this is a result from one source choosing a wrong base for the completion options of the other source. Every time a trigger character is inserted, there will be **2 runs of completion**. The first run will give the completion menu correctly, but the second run will close it. The second run would choose a wrong base and that base will filter out all completion options, so it will not open a new completion menu.

For example, in the scenario I tested under, when a `.` is inserted,  the autocmd `TextChangedI` would fire and the **first run** would start. `s:matches` is a dictionary that include sources that should provide completion options. A source will be used only if its `s:matches` entry is updated. Both `asyncomplete-lsp` and `file`'s entry in `s:matches` will be updated in this run by the following lines:

*The trigger character part of `s:on_change`*

https://github.com/prabirshrestha/asyncomplete.vim/blob/b65b77bd753ae75bedf31f9153fdd9d2bd4711be/autoload/asyncomplete.vim#L253-L262

The completion would be done correctly as both sources have the same `startcol`. `startcol` is a value used to decided completion base. Same `startcol` means same completion base.

The first run of completion would call `complete()`, and the autocmd `TextChangedP` would fire. This is a **second run** of completion and closes the first completion menu. This time, `file`'s entry in `s:matches` will not be updated by the *trigger character character part of `s:on_change`* mentioned above, as the context has not changed.

*Because the context has not changed, this condition is not satisfied for `file`*:

https://github.com/prabirshrestha/asyncomplete.vim/blob/b65b77bd753ae75bedf31f9153fdd9d2bd4711be/autoload/asyncomplete.vim#L257

`lsp`'s entry would be updated, though.

`lsp`'s `startcol` was updated here:

https://github.com/prabirshrestha/asyncomplete.vim/blob/b65b77bd753ae75bedf31f9153fdd9d2bd4711be/autoload/asyncomplete.vim#L321

Because its `startcol` has been changed, making it different from `col` in the context, the condition mentioned above will be satified. `lsp`'s entry in `s:matches` will be updated, and `lsp` will do completion correctly.

After that, the part checking if the refresh pattern matches the source will update `file`'s entry, as `.` matches the refresh pattern and gives a new startcol.

*These lines will modify `file`'s entry in `s:matches` and give it a small `startcol`:*

https://github.com/prabirshrestha/asyncomplete.vim/blob/b65b77bd753ae75bedf31f9153fdd9d2bd4711be/autoload/asyncomplete.vim#L265-L282

Since this startcol is smaller, it will be used in `s:recompute_pum` to decide the base.

https://github.com/prabirshrestha/asyncomplete.vim/blob/b65b77bd753ae75bedf31f9153fdd9d2bd4711be/autoload/asyncomplete.vim#L390-L398

The base in this case would be `.`. Since it matches no completion option provided by `lsp`, all options will be filtered out (at least this is what happens in the default preprocessor; I think other reasonable preprocessors should not use `.` as a base either, though).

This does not happen in Vim (at least under the version I tested on: version 8.1.1186) because in Vim, `complete()` called from a timer does not trigger `TextChangedP`, so the second run mentioned which causes the wrong base to be given is not performed. I suspect this is a bug of Vim.

I suggest that `\.`, `>` and `:` should be deleted from the refresh pattern. Those characters will always be the bases in the current design when refresh pattern is used to match sources, and I think they should never be. 

PR: #142

**Comment by niklaas** [comment]
Thanks for your thorough analysis and referencing issue #138 that I submitted. Would you mind pointing to the exact lines of code that you are referring to, see https://help.github.com/en/articles/creating-a-permanent-link-to-a-code-snippet? Maybe we can work on a bug fix together.

**Comment by simeir** [comment]
> Thanks for your thorough analysis and referencing issue #138 that I submitted. Would you mind pointing to the exact lines of code that you are referring to, see https://help.github.com/en/articles/creating-a-permanent-link-to-a-code-snippet? Maybe we can work on a bug fix together.

I updated the comment. Hope it's more readable now. I actually have submitted a PR for this problem. You can checkout [this branch](https://github.com/simeir/asyncomplete.vim/tree/nvim-flicker-certain-scenario) and see if it solves the problem also for you.

**Comment by prabirshrestha** [comment]
@niklaas Can you try merging both the branches locally and verify. I should be able to try it during the weekend.

**Comment by simeir** [comment]
The 2 PRs actually would cause a conflict. I submitted them as 2 PRs because they address different problems. Would you think it is a good idea for me to merge them locally and submit a new PR?

**Comment by prabirshrestha** [comment]
Can you send another PR with both combined? I will have a look at it in more details during the weekend.

**Comment by simeir** [comment]
Just sent that merged PR.

**Comment by niklaas** [comment]
@simeir thanks for updating the description. I haven't had time to follow it through but I checked out your PR. It seems it solves the issue when `g:asyncomplete_auto_popup` is enabled; that said, the completion menu no longer opens when `g:asyncomplete_auto_popup` is disabled and `<Plug>(asyncomplete_force_refresh)` is triggered.

**Comment by simeir** [comment]
@niklaas I forgot to fix the base being wrong in force refresh. Thank you for pointing that out. I pushed a new commit and it should work now.

**Comment by niklaas** [comment]
@simeir great this works much better now. There is one thing I have still noticed though:

I have `set omnifunc=lsp#complete` just to counter check whether `asyncomplete.vim` works correctly. If there is only whitespace (or nothing) before the cursor `<c-x><c-o>` (triggering `omnifunc`) shows completions. However, triggering `<Plug>(asyncomplete_force_refresh)` doesn't show anything.

That said, if I have `g:asyncomplete_auto_popup` enabled, the completion menu also only shows after deleting characters and because of this there is only whitespace in front of the cursor. So maybe this is expected behavior or another bug.

**Comment by simeir** [comment]
@niklaas I just pushed a fix for that. It is sort of a different problem from what I am trying to solve here. The problems had existed already before I did all those previous fixes, but did not cause any syndrome without those fixes...

**Comment by niklaas** [comment]
@simeir thank you. No need to fix everything in your PR though. :-) I hope, I'll find some time to take a look at your code next week. I'm interested in how you solved the issue.
