### ISSUE TITLE
How do I only autocomplete on "."

### ISSUE THREAD

**Issue by jyapayne** [prabirshrestha/asyncomplete.vim#143]
I only want to autocomplete on the `.` character and nothing else. How do I accomplish this? I tried modifying the existing example for tab completion, but it doesn't do quite what I want (I'm a noob at vimscript). Basically, whenever I type `.`, I want a list of completions to popup on that objects methods.

**Comment by simeir** [comment]
Using this line in your vimrc might help
```
imap <silent> . .<Plug>(asyncomplete_force_refresh)
```

**Comment by prabirshrestha** [comment]
Please try the latest master. When you regsiter a source you can add custom `triggers`.

```vim
au User asyncomplete_setup call asyncomplete#register_source({
    \ 'name': 'mylanguage',
    \ 'whitelist': [*],
    \ 'completor': function('s:completor'),
    \ 'triggers': { '*': ['.'] },
    \ })
```

Where key is filetype or `*` for all filetypes and value is array of trigger character. You can also put multiple characters which is popular in some languages such as c++ but it will automatically only use the last char from that trigger char. `'triggers': { '*': ['.'], 'cpp': ['.', '->', '::'] }`
