### ISSUE TITLE
Autocomplete only triggers after file save

### ISSUE THREAD

**Issue by edgard** [prabirshrestha/asyncomplete.vim#149]
Apparently the autocompletion is only triggering after you save a file, is this the expected behavior?

Neovim v0.3.7

Demo here:
https://asciinema.org/a/6KhGhjYkUYNlN8Ue8WtA82XEF

Minimal config used:
```
" plugins
call plug#begin('~/.local/share/nvim/plugged')
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'
Plug 'prabirshrestha/asyncomplete-file.vim'
call plug#end()

" asyncomplete
call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
        \ 'name': 'buffer',
        \ 'whitelist': ['*'],
        \ 'completor': function('asyncomplete#sources#buffer#completor'),
        \ }))
call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
        \ 'name': 'file',
        \ 'whitelist': ['*'],
        \ 'completor': function('asyncomplete#sources#file#completor')
        \ }))

```

**Comment by prabirshrestha** [comment]
can you try some other sources such as omni or neco syntax since both buffer and file do have some issues. Also can you try b65b77bd753ae75bedf31f9153fdd9d2bd4711be commit

**Comment by edgard** [comment]
Yeah, you're right. it does work with other sources. Seems to be related to buffers.

I can't find anything on your commit that seems related? It's a readme modification. :)

**Comment by prabirshrestha** [comment]
Buffer source is currently very bad. I have always wanted to redo it but since I don’t use it much haven’t invested there much.
