### ISSUE TITLE
ALE as the LSP Source

### ISSUE THREAD

**Issue by amadeus** [prabirshrestha/asyncomplete.vim#150]
Would it be possible to use ALE as the LSP autocomplete source? I already use it for other LSP related items, alongside prettifying and linting. It would be great to not have to load 2 plugins connecting to the LSP.

**Comment by DonnieWest** [comment]
I've not used it, but it looks like https://github.com/andreypopp/asyncomplete-ale.vim might do what you want. It seems to rely on ale internals though and could break at any time. It would probably be best to integrate with ale directly

**Comment by prabirshrestha** [comment]
No plans to support it. You can read my thoughts as well as the author of ALE thoughts on https://github.com/w0rp/ale/issues/517#issuecomment-320489193 and https://github.com/w0rp/ale/issues/1340.

**Comment by DonnieWest** [comment]
@prabirshrestha after looking over the conversations, it doesn't seem out of question to add asyncomplete to ALE just like there's a deoplete source. Is that your understanding?

If so, I might follow up with the ALE folks and see if I can get that going. When I actually get some time that is :D

**Comment by prabirshrestha** [comment]
Yes. It should be possible if ALE provides api. Here is another thread about it https://github.com/Quramy/tsuquyomi/issues/140 https://github.com/Quramy/tsuquyomi/pull/144.

The original thread was related to ALE diagnostics which is bit different compared to this.
