### ISSUE TITLE
Asyncomplete filters source completions that are valid

### ISSUE THREAD

**Issue by DonnieWest** [prabirshrestha/asyncomplete.vim#151]
Problem:

Asyncomplete appears to be filtering out certain completion types when triggers are typed. This only happens when there are multiple sources available on a single filetype and they are generating different `startcol`

This can be seen in code here

https://github.com/prabirshrestha/asyncomplete.vim/blob/master/autoload/asyncomplete.vim#L422

Which is used to calculate an incorrect base later on here

https://github.com/prabirshrestha/asyncomplete.vim/blob/master/autoload/asyncomplete.vim#L441

Since the base is incorrect, the filters remove correct completions for certain source types. In my case, `vim-lsp` and `asyncomplete-file` conflict on javascript files and when I type `console.` the base generated is `console.` instead of an empty string. Since no completion can match that string, all completions are removed and nothing shows up as a completion option.

This may just be a bug in how `asyncomplete-file` generates `startcol`. I've not gotten that far yet :D

Replication steps:

https://asciinema.org/a/bauATtxxnDQFU3Ebo5qYOLKeO

Minimal vimrc
```
" Install Vim Plug if not installed
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'
let g:node_host_prog = '/home/igneo676/bin/neovim-node-host'
call plug#begin()


Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-file.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'

"Javascript Plugins
Plug 'pangloss/vim-javascript'
Plug 'maxmellon/vim-jsx-pretty'

call plug#end()

imap <C-x><C-o> <Plug>(asyncomplete_force_refresh)
au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
    \ 'name': 'file',
    \ 'whitelist': ['*'],
    \ 'priority': 100,
    \ 'completor': function('asyncomplete#sources#file#completor')
    \ }))

let g:lsp_signs_enabled = 0
let g:lsp_diagnostics_echo_cursor = 1

if executable('typescript-language-server')
    au User lsp_setup call lsp#register_server({
      \ 'name': 'javascript support using typescript-language-server',
      \ 'cmd': { server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
      \ 'root_uri': { server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_directory(lsp#utils#get_buffer_path(), '.git/..'))},
      \ 'whitelist': ['javascript', 'javascript.jsx']
      \ })
endif
```

**Comment by DonnieWest** [comment]
Posting since I'm wrapping up for the night and still unsure of the best approach. I'm thinking the best route would be to just filter each source based on what it thinks the `startcol` and `base` are and merge the results at the end. I might be way off though 😅

**Comment by DonnieWest** [comment]
I think I have it figured out - it turns out, the `startcol` asyncomplete keeps track of is the same regardless of whether a given source provides completions. Ideally, asyncomplete would use each source's `startcol` to handle filtering during preprocessing and allow preprocessing to determine a `startcol` to use for all valid sources

Hopefully that makes sense :P

PR coming tonight to hopefully fix this

**Comment by amadeus** [comment]
Woots! Very much looking forward to this fix!

**Comment by DonnieWest** [comment]
@amadeus ask and ye shall receive :dancer:
