### ISSUE TITLE
Autocomplete Trait signature?

### ISSUE THREAD

**Issue by xoac** [prabirshrestha/asyncomplete.vim#161]
I saw similar question on [reddit](https://www.reddit.com/r/rust/comments/dc7fva/vim_autocomplete_trait_signature_does_a_plugin/) and I am curious this can be done by this plugin. It would be so helpful!

It's possible to use rust-analyzer instead of rls?

**Comment by prabirshrestha** [comment]
[vim-lsp-settings](https://github.com/mattn/vim-lsp-settings) defaults to rust analyzer and I use it everyday so should work.
