### ISSUE TITLE
Sort precessor in the document breaks triggering completion menu with different sources

### ISSUE THREAD

**Issue by chengzeyi** [prabirshrestha/asyncomplete.vim#162]
https://github.com/prabirshrestha/asyncomplete.vim/blob/db3ab51ef6d42ac410afaea53fc0513afd0d5e25/doc/asyncomplete.txt#L112

Hi, there.
It seemed that when I wanted to sort the completion items by priority according to the document, the completion menu did not pop up after pressing the trigger character ('.', '>' or ':'). I used the file source and lsp source, and everything went OK after I removed the file source temperately.

I think the problem is related to the wrong base. That is, the base is changed after each different source returns the items and calls the preprocessor. I fix the problem by using a strategy similar to the default processor to decide the base.

```vim
    function! s:sort_by_priority_preprocessor(options, matches) abort
        let l:items = []
        let l:startcols = []
        for [l:source_name, l:matches] in items(a:matches)
            let l:startcol = l:matches['startcol']
            let l:base = a:options['typed'][l:startcol - 1:]
            for l:item in l:matches['items']
                if stridx(l:item['word'], l:base) == 0
                    let l:startcols += [l:startcol]
                    let l:item['priority'] =
                                \ get(asyncomplete#get_source_info(l:source_name), 'priority', 0)
                    call add(l:items, l:item)
                endif
            endfor
        endfor

        let a:options['startcol'] = min(l:startcols)
        let l:items = sort(l:items, {a, b -> b['priority'] - a['priority']})

        call asyncomplete#preprocess_complete(a:options, l:items)
    endfunction
```

**Comment by prabirshrestha** [comment]
sort_by_priority_preprocessor no longer exists. this needs to be done by custom preprocessor now.
