### ISSUE TITLE
Cannot enter new lines when suggestions are shown.

### ISSUE THREAD

**Issue by DasOhmoff** [prabirshrestha/asyncomplete.vim#163]
Hello,

when asyncomplete shows me some completion suggestions, I cannot enter new lines or insert a new line. It basically does nothing and just flashes the suggestion box.
For example, what I would like to happen:
![grafik](https://user-images.githubusercontent.com/16063186/68076207-edabaa80-fdb1-11e9-8b4f-5ebc925710db.png)
(Basically adding a new line and moving to the start of the line. But instead, it just flahes the suggestion box and does nothing else.

How can I solve that, so it actually just enters a new line when I have not selected any of the completion suggestions?

**Comment by prabirshrestha** [comment]
Can you try this?

```vim
inoremap <expr> <CR> pumvisible() ? asyncomplete#close_popup() . "\<CR>" : "\<CR>"
```

You can see the discussion at https://github.com/prabirshrestha/asyncomplete.vim/issues/117 and  https://github.com/prabirshrestha/asyncomplete.vim/issues/85

**Comment by DasOhmoff** [comment]
Thank you very much!
