### ISSUE TITLE
Fuzzy autocompletion?

### ISSUE THREAD

**Issue by DasOhmoff** [prabirshrestha/asyncomplete.vim#165]
Hello,

is there a way to make the auto completion fuzzy?
For example if I type: "strng", that also "string" is suggested for auto completion?

Thank you.

**Comment by prabirshrestha** [comment]
You will need to use other plugins or can write your own. There are no plans to support fuzzy search out of the box.

https://github.com/tsufeki/asyncomplete-fuzzy-match
https://github.com/machakann/asyncomplete-ezfilter.vim

https://twitter.com/mattn_jp/status/1195278541656473601

**Comment by prabirshrestha** [comment]
This is now available in vim via https://github.com/prabirshrestha/asyncomplete.vim/pull/246. Neovim doesn't have `matchfuzzypos` yet. It is current in PR.
