### ISSUE TITLE
Does not complete from current buffer when first opening files

### ISSUE THREAD

**Issue by jackkinsella** [prabirshrestha/asyncomplete.vim#172]
Hi, 

I've been using `asyncomplete` for a few weeks and am v. happy with the `lsp` integration. I noticed a snag, however, with non-lsp autocomplete of the current buffer. 

Perhaps you feel this is out of scope, but I'd argue that current buffer completion is a feature of autocomplete that most programmers would intuitively expect.

#### Reproduction steps

Open a file from the command line:

`$ nvim my_existing_file.random_ending`

Type a word from the file. It will not autocomplete. 

By contrast, Vim's built-in `<C-x><C-p>` works just fine.

(I also tried with the `aysnccomplete/buffers` plugin and this suffers from the same issue.)

#### Related issues

When you open a brand new file from an existing VIM process, there is also no autocompletion of this new buffer. The problem persists even after saving the file. 

The way to get things working here, assuming the buffers plugin is loaded, is to type `:e` to load the file again and trigger `BufWinEnter`.

**Comment by jmdevin** [comment]
I also encountered this on vim 8.2 with the asyncomplete-buffer.vim plugin installed. When I first open vim, results from the current buffer will not appear for completion. I need to 're-open' the buffer and then they appear.

**Comment by ipkiss42** [comment]
I think this is a bug in the buffer plugin, not in asyncomplete.vim

See the [issue](https://github.com/prabirshrestha/asyncomplete-buffer.vim/issues/17) I created there for a workaround.

**Comment by beavailable** [comment]
This is a bug and I have fixed it, See #265
