### ISSUE TITLE
Not trigger completion after textEdit

### ISSUE THREAD

**Issue by hrsh7th** [prabirshrestha/asyncomplete.vim#173]
I'm using asyncomplete now, thanks for providing this plugin.

I met the problem that is not trigger completion after apply additionalTextEdit.

I investigated to the problem tjen I found the reason.

The reason is https://github.com/prabirshrestha/asyncomplete.vim/blob/master/autoload/asyncomplete/utils/_on_change/textchangedp.vim#L54.

I don't know the solution, thinking it now.

**Comment by hrsh7th** [comment]
Currently my workaround are https://github.com/hrsh7th/asyncomplete.vim/commit/ead63555a745140af50584f5912687fb34c9d68a.

But it is not respect existing code and existing comments.
I like my workaround behavior, but I don't know that has possibility problem.
So I report it only for now.

**Comment by prabirshrestha** [comment]
What if you try v1. It had old way to detect changes

**Comment by prabirshrestha** [comment]
https://github.com/prabirshrestha/asyncomplete.vim/tree/v1.7

**Comment by hrsh7th** [comment]
I check v1.7 then trigger completion as expected (but item is not sorted expectedly).

**Comment by hrsh7th** [comment]
The `additionalTextEdits` will add line for above of current line.
We can't distinguish below changes.

1. Adding new line by `additionalTextEdits`.
2. `<CR>` to the next line.
3. `<BS>` to the prev line.

Currently implementation was checking cursor line changes to care about the 2, 3 cases.
