### ISSUE TITLE
Ctrl-L does not insert a character from the current match?

### ISSUE THREAD

**Issue by idbrii** [prabirshrestha/asyncomplete.vim#177]
Normally, using vim's ins-completion, you can use C-L to narrow down your search:

`:help ins-completion-menu`:

> CTRL-L		  Add one character from the current match, may reduce the number of matches.

But when using asyncomplete, you cannot. Instead, it inserts a `^L` character (like normally pressing Ctrl-L in insert mode). If I manually invoke omnicompletion with Ctrl-x Ctrl-o, I can use Ctrl-L as expected. I don't understand what's special about asyncomplete's popup menu.

----

Tested with a minimal config:

```
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()
```

plugins and versions:

asyncomplete.vim prabirshrestha/asyncomplete.vim@db3ab51 Added financial contributors to the README 
prabirshrestha/vim-lsp@b9e6816 Use prefix filter when does not specified 
prabirshrestha/asyncomplete-lsp.vim@9e7b249 Fix calculating startcol 
tpope/vim-fugitive@590c8d7 Add an undo command to blame windows
prabirshrestha/async.vim@f67ecb5 Support 'cwd' option in jobstart
mattn/vim-lsp-settings@d2f5a63 Support svn, hg, bzr as root markers
tpope/vim-pathogen@e7857be Avoid line continuations for 'compatible' interop
tpope/vim-sensible@7aa7dba Fix grammar error

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 21 2020 23:02:39)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-140

**Comment by idbrii** [comment]
Is there any more information I can add to help?

**Comment by prabirshrestha** [comment]
I'm not sure how this would work. We need to intercept `<c-l>` and then passthrough. But it doesn't seem to work.

```vim
 inoremap <expr> <C-l> ("\<C-l>")
```

other keys works.

```vim
inoremap <expr> <C-j> ("\<C-n>")
inoremap <expr> <C-k> ("\<C-p>")
```

wondering if this is more of a vim issue. 

asyncomplete.vim uses `:h complete()` which is different from omni func.

**Comment by idbrii** [comment]
Thanks for that info! Reported it as a vim bug.
