### ISSUE TITLE
Feature request(s)

### ISSUE THREAD

**Issue by highend** [prabirshrestha/asyncomplete.vim#18]
Great addon, thanks a lot for creating it! I'm currently use it together with
asyncomplete-buffer.vim. Fuzzy-matching capabilities and it's really a lightweight one!

Some feature requests (if you don't mind...):

01. Please add an option to show the completion window on a minimum of  <x> written characters

E.g. (default value): let g:asyncomplete_popup_on_minimum_characters = 0

I for myself would set that option to 3 so you'd need to type 3 characters before the autocomplete popup appears

02. Keep the popup open after invoking it (with <tab> or ctrl+space) when let g:asyncomplete_auto_popup = 0 is used
Atm the popup closes automatically if you type more to narrow down the result list

03. If there is only one possible match, don't show the popup first (with that single entry) but automatically autocomplete the item immediately

Ofc as an option, e.g.: let g:asyncomplete_complete_on_single_match = 1

04. Would it be possible to make the entries of the popup more context aware?
Atm all entries are "only" alphabetically sorted. But if an entry is near the current typing position it should
have a higher priority than one that would fit what you currently typed but is farther away (position wise)

**Comment by prabirshrestha** [comment]
I'm curios for what language you use buffer completion. Or do you use it for plain text.

**Comment by highend** [comment]
Atm I use it for *.ahk (AutoHotkey) and *.xys (a scripting language for the XYplorer file manager)

**Comment by prabirshrestha** [comment]
@highend Some of your feature requests are now supported. Refer to https://github.com/prabirshrestha/asyncomplete.vim/pull/49 for more details. Feedback welcome

> Please add an option to show the completion window on a minimum of written characters
E.g. (default value): let g:asyncomplete_popup_on_minimum_characters = 0

You can now use `let g:asyncomplete_min_chars = 3`

>Would it be possible to make the entries of the popup more context aware?
Atm all entries are "only" alphabetically sorted. But if an entry is near the current typing position it should
have a higher priority than one that would fit what you currently typed but is farther away (position wise)

If you have vim with lua, Smart (fuzzy) completion is enabled. `let g:asyncomplete_smart_completion = 0`. Not exactly what you requested but should be lot better then what is now supported.

**Comment by prabirshrestha** [comment]
Minchars and custom filter func will be supported in asyncomplete.vim
