### ISSUE TITLE
Some additional configuration is required?

### ISSUE THREAD

**Issue by 097115** [prabirshrestha/asyncomplete.vim#187]
I have the following in my $VIMRC:

    call plug#begin('~/.vim/plugged')
    Plug 'prabirshrestha/async.vim'
    Plug 'prabirshrestha/asyncomplete.vim'
    Plug 'prabirshrestha/asyncomplete-buffer.vim'
    Plug 'prabirshrestha/asyncomplete-tags.vim'
    call plug#end()

But simply nothing happens? `echo g:asyncomplete_auto_popup` reports `1`, though. Vim 8.2.205.

**Comment by prabirshrestha** [comment]
you need to register source. refer to docs.
