### ISSUE TITLE
autocomplete popupmenu cover the vim-lsp's preview window

### ISSUE THREAD

**Issue by chenjie199234** [prabirshrestha/asyncomplete.vim#190]
i'm using vim-lsp to provide lsp function
but there is a problem
i report it at here
maybe this problem is called by asyncomplete.vim
so i link it to here
https://github.com/prabirshrestha/vim-lsp/issues/745

**Comment by mitinarseny** [comment]
I am facing this problem with intersecting `signature-help` from `vim-lsp` and autocomletion menu from `asyncomplete.vim`. Wouldn't it be nice to move `signature-help` above the current line instead of below?

**Comment by mitinarseny** [comment]
https://github.com/prabirshrestha/vim-lsp/issues/745#issuecomment-609410224
