### ISSUE TITLE
auto complete with vim-lsp and eclipse lsp is slow and causes freezes

### ISSUE THREAD

**Issue by husainaloos** [prabirshrestha/asyncomplete.vim#192]
Hello,

I am using vim-lsp with vim-lsp-settings. I am developing in java. vim-lsp works fine without any problems. However, when enable auto complete, I noticed that vim freezes are unpredictable times.

It does not matter if I am writing a comment in java, or code, or adding a ".". it freezes unpredictably for a second or two, and then it pulls a completion list. Sometimes it freezes in the middle of typing a word.

I do not know if this is common, or related to my setup with java.

I do not have any unusual configuration for LSP beside the following:

```
	let g:lsp_log_verbose = 1
	let g:lsp_log_file = expand('/tmp/vim-lsp.log')

	inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
	inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
	inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"

	function! s:check_back_space() abort
	    let col = col('.') - 1
	    return !col || getline('.')[col - 1]  =~ '\s'
	endfunction

	inoremap <silent><expr> <TAB>
	  \ pumvisible() ? "\<C-n>" :
	  \ <SID>check_back_space() ? "\<TAB>" :
	  \ asyncomplete#force_refresh()
	inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

	set omnifunc=lsp#complete

	nnoremap <silent> K :LspHover<CR>
	nnoremap <silent> gd :LspDefinition<CR>
	nnoremap <silent> <localleader>lr :LspRename<CR>
	nnoremap <silent> <localleader>la :LspCodeAction<CR>
	nnoremap <silent> <localleader>li :LspImplementation<CR>
	nnoremap <silent> <localleader>lf :LspDocumentFormat<CR>
```

**Comment by aantonello** [comment]
I believe the problem lies in `asyncomplete-lsp`. More specifically on its `s:handle_completion` function, in this line.

~~~{vim}
call map(l:items, 'lsp#omni#get_vim_completion_item(v:val, a:server_name)')
~~~

Happens that some completions result in a large number of elements. 10,000, 20,000, 30,000 or more. Since this function is synchronous, mapping to a large number of elements causes a noticeable delay.

**Comment by ryanbrate** [comment]
I've just started using vim-lsp, vim-lsp-settings, asycomplete and asycomplete-lsp today with python. (moving from ycm)
I imagine the problem I'm seeing is the same as the op. There's a clear delay between typed input, and appearance of the characters/ completion suggestions.
