### ISSUE TITLE
RFE: add b:asyncomplete_auto_popup

### ISSUE THREAD

**Issue by mkoura** [prabirshrestha/asyncomplete.vim#193]
It would be great to have `b:asyncomplete_auto_popup`. I don't want to have automatic popup for some filetypes (text, markdown, rst) and for other filetypes it's nearly unusable (e.g. fugitive with github/gitlab plugin queries for issues etc. to autocomplete in the `gitcommit` buffer and the input is lagging a lot). Having possibility to set auto popup per buffer would be great.

Now I have this workaround
```vim
  let s:no_auto_popup = ['gitcommit', 'markdown', 'rst', 'text']
  au InsertEnter * exe 'let g:asyncomplete_auto_popup = '.(index(s:no_auto_popup, &ft) >= 0 ? '0' : '1')
```

Thanks for great plugin btw!

**Comment by prabirshrestha** [comment]
Sounds like a good idea. Feel free to send a PR.
