### ISSUE TITLE
Errors on switching to terminal window in insert mode

### ISSUE THREAD

**Issue by mitinarseny** [prabirshrestha/asyncomplete.vim#196]
Open terminal window in neovim:
```vim
vsp | term
```
Go back to ordinary window, start insert mode there and click with mouse on terminal window:
![image](https://user-images.githubusercontent.com/10659110/79169572-7749b480-7df5-11ea-9a28-f1b1d63d8213.png)

**Comment by prabirshrestha** [comment]
This should be fixed in master so please try again.
