### ISSUE TITLE
"E730: using List as a String" when used with vim-iced-asyncomplete

### ISSUE THREAD

**Issue by victorb** [prabirshrestha/asyncomplete.vim#197]
Trying to asyncomplete.vim but getting this error when the autocomplete appears. 

Full error:
```
line   17:
E730: using List as a String
Error detected while processing function <SNR>35_recompute_pum[43]..<SNR>35_default_preprocessor[24]..asyncomplete#preprocess_complete:
```

**Following versions are being used:**
- neovim `v0.4.3`
- https://github.com/liquidz/vim-iced/ commit `de78382`
- https://github.com/prabirshrestha/asyncomplete.vim `5713fa6`
- https://github.com/liquidz/vim-iced-asyncomplete `9979a1e`
- OS: Arch Linux x86_64
- Kernel Release: 5.6.3-arch1-1

**neovim -v:**

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

`:checkhealth` shows that everything is correctly setup.

**nvimrc**

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'junegunn/fzf' " same error with ctrl-p, seems unrelated

Plug 'guns/vim-sexp',    {'for': 'clojure'}
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'liquidz/vim-iced', {'for': 'clojure'}
Plug 'liquidz/vim-iced-asyncomplete', {'for': 'clojure'}
call plug#end()

let g:iced_enable_default_key_mappings = v:true

```

Error happens but exiting the error prompt shows an correct autocomplete, for a couple of times, until it seems to break after 2-3 of the error popping up. 

Unsure of what extra information is needed to debug/troubleshoot this issue. Unsure if the error actually comes from this plugin, but because it's mentioned by name in the error, thought I'd try here before. Greatly appreciate any pointers how I can debug/troubleshoot further to find where the error is.

**Comment by prabirshrestha** [comment]
please provide asyncomplete logs and I can reopen the issue.
