### ISSUE TITLE
High latency of function calls

### ISSUE THREAD

**Issue by tmpm697** [prabirshrestha/asyncomplete.vim#199]
I do vim profile and `asyncomplete.vim` is the only one that I observe `high` latency when call its functions:
```
FUNCTION  <SNR>70_maybe_notify_on_change()
    Defined: ~/.vim/pack/default/start/asyncomplete.vim/autoload/asyncomplete/utils/_on_change/textchangedp.vim:56
Called 5 times
Total time:   0.131253
 Self time:   0.000768

count  total (s)   self (s)
                                " enter to new line or backspace to previous line shouldn't cause change trigger
    5              0.000057     let l:previous_position = s:previous_position
    5              0.000064     let s:previous_position = getcurpos()
    5              0.000113     if l:previous_position[1] ==# getcurpos()[1]
   10              0.000164         for l:Cb in s:callbacks
    5   0.130689   0.000204             call l:Cb()
   10              0.000061         endfor
    5              0.000008     endif
```
and
```
FUNCTION  <SNR>70_on_text_changed_i()
    Defined: ~/.vim/pack/default/start/asyncomplete.vim/autoload/asyncomplete/utils/_on_change/textchangedp.vim:42
Called 5 times
Total time:   0.133359
 Self time:   0.000707
```

Specs:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 19 2020 11:25:00)
Included patches: 1-129
Compiled by Arch Linux
```

latest version of this plugin.

I expect somehow the latency about 0.00xxxxx or at least 0.0yyyyy

I don't know if I expect too much but as a user I want to lower the cost of performance and latency.

**Comment by prabirshrestha** [comment]
That means one of your source is slow. Are you using vim-lsp or buffer sources? If you are using vim-lsp do give this branch a try though you need to have vim/neovim with lua supported. https://github.com/prabirshrestha/vim-lsp/pull/821

**Comment by tmpm697** [comment]
Will give it a try, I use vim-lsp.

**Comment by prabirshrestha** [comment]
It is merged. Please try the latest master. Also if u have lua it fallbacks to lua for diff. We have seen around 6x perf improvements there. You should also look at vim-lsp profiles since most of the bottleneck could most likely be there.

**Comment by prabirshrestha** [comment]
Made a few more changes to improve perf just by a bit.

 https://github.com/prabirshrestha/vim-lsp/pull/822
https://github.com/prabirshrestha/asyncomplete-lsp.vim/pull/32

I'm closing this and starting to track it here instead. https://github.com/prabirshrestha/vim-lsp/issues/823
