### ISSUE TITLE
asyncomplete v3

### ISSUE THREAD

**Issue by prabirshrestha** [prabirshrestha/asyncomplete.vim#200]
Some of my thoughts on what the asyncomplete vnext (i.e. v3) should do.

Asyncomplete is pretty much done as there aren't many big features to add but one thing that keeps bothering me is the performance. This is mostly attributed to asyncomplete sources and not asyncomplete it self but given that there has been interesting traction going in both vim and neovim side it would be good if can revisit this. I recently sent a [PR](https://github.com/vim/vim/pull/6063) for vim to add first class support for `vim.call` and `vim.fn.*` which is similar to neovim and was merged. Bram also seems to be open to merging good changes like this that will help the lua interface. If we can have a PR in vim to support transferring between lua functions and vim functions seemlessly seems like a good opportunity to migrate asyncomplete.vim to lua for perf. I have also thought of having vimscript support stdin/stdout/stderr so one could remotely talk which is could be better even if we move to faster languages such as lua.  And if neovim support remote lua interface it could even be better. Asyncomplete will always work with just vimscript so folks don't need to worry about it but this gives an opportunity for folks who have lua enabled to have a faster completion engine instead of being blocked by vimscript perf.

Another important feature that bothers me is the lack of cancellation support. While no one seems to have complained about it it is something that could improve perf. This will most likely change the completor interface but since I do want it to be backwards compact I will only change it for lua. https://github.com/prabirshrestha/callbag.vim https://github.com/prabirshrestha/lua-callbag

I have started to make the v3 branch open to public though nothing there works but gives an idea on where I would like to go. https://github.com/prabirshrestha/asyncomplete.vim/tree/v3. Currently the biggest blocker is calling vim functions from lua that takes in callbacks as functions in lua script without writing any vimscript.

Related issues that can be solved.
* [High latency of function calls #199](https://github.com/prabirshrestha/asyncomplete.vim/issues/199)
* Better default preprocess has been asked several times. by @mattn https://github.com/prabirshrestha/asyncomplete.vim/pull/185. 
* Some seems to miss the default fuzzy filter which existed when lua is enabled. Might be good to bring it back.

Improving sources:
There are some plugins such as buffer which is very slow would be good to migrate this to using listener events.

**Comment by astier** [comment]
+1 for fuzzy
