### ISSUE TITLE
set g:asyncomplete_auto_completeopt default to 0

### ISSUE THREAD

**Issue by squm** [prabirshrestha/asyncomplete.vim#205]
You added `g:asyncomplete_auto_completeopt` which overrides `completeopt` vim settings, it took time to figure out what messes with settings. Don't do this anymore, add new “features” with default value of “0”

**Comment by Shougo** [comment]
I think the option is needed.
Because if completeopt is not set properly, the auto completion doesn't work.

You should not change the value if don't understand about completeopt.

**Comment by astier** [comment]
I also think this shouldn't be set by default. It should respect completeopt of the user.

**Comment by astier** [comment]
It actually broke `<cr>` because of `noselect` and I couldn't select the first suggestion. I almost gave up on this plugin just because of this. I think users can decide on their own how they want to set completeopt. If its necessary to function correctly then write it in the readme and say that the user needs to set completeopt accordingly.

**Comment by Shougo** [comment]
>  It should respect completeopt of the user.

`completeopt` should be respented, yes.  But if user's completeopt does not work with auto complete plugin, the plugin must change `completeopt` unfortunately.

> I think users can decide on their own how they want to set completeopt. 

You can change the behavior by `g:asyncomplete_auto_completeopt` option.

https://github.com/prabirshrestha/asyncomplete.vim/blob/91ac1f6e6ff4952aef6004880f7129ca6d3f4823/doc/asyncomplete.txt#L47

Hm... It seems fixed option overwrite behavior, I think deoplete behavior is better though.
It does not overwrite `noselect,noinsert` if not needed.

**Comment by astier** [comment]
> Hm... It seems fixed option overwrite behavior, I think deoplete behavior is better though.
It does not overwrite noselect,noinsert if not needed.

Yes it should not overwrite those settings. Otherwise, it can lead to a lot of confusion. In this respect deoplete works better.
