### ISSUE TITLE
I fixed problem of enter key while popup is open on nvim

### ISSUE THREAD

**Issue by jibuntu** [prabirshrestha/asyncomplete.vim#211]
This problem happen when using **neovim**. 
There isn't problem when using vim.

## My problem
![Peek 2020-08-03 03-38](https://user-images.githubusercontent.com/33652019/89129774-03b1eb80-d53b-11ea-9aad-7b115940a2b0.gif)
I pushed enter key, but didn't close popupmenu.

## After fix problem
![Peek 2020-08-03 03-39](https://user-images.githubusercontent.com/33652019/89129912-0fea7880-d53c-11ea-9820-c575acac267c.gif)

## Edited code by me
https://github.com/jibuntu/asyncomplete.vim/blob/f175edb2877ccf565d496d67bc1542970e0cec3e/autoload/asyncomplete.vim#L140-L157

This is my commit that was fixed problem.
https://github.com/jibuntu/asyncomplete.vim/commit/f175edb2877ccf565d496d67bc1542970e0cec3e

**Comment by AlexBerimbolo** [comment]
i have the same problem, pressing enter doesnt close the popup, forcing me to press space, then enter to go to next line.  I am on vim, not nvim

**Comment by ii41** [comment]
This doesn't happen to me on either vim or nvim.

Perhaps you copied this line from README into your vimrc?
```
inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"
```

Either way I think this isn't something that should be fixed in this project. If it's only happening on nvim it's probably a bug in nvim.

**Comment by prabirshrestha** [comment]
There is nothing wrong with adding extra inoremap in vimrc. This is actually quite common and some actually prefers different behavior so I would like to avoid asyncomplete dictating what users should do.

If you would like to improve docs feel free to send a PR to docs instead.
