### ISSUE TITLE
Spaces don't start new completion word

### ISSUE THREAD

**Issue by jsit** [prabirshrestha/asyncomplete.vim#212]
Something I overlooked with #135. A non-keyword character should close a previously opened menu, but that's not happening; instead it stays open until the minimum characters have been typed in the next word:

<img width="191" alt="Screen Shot 2020-08-09 at 2 52 01 PM" src="https://user-images.githubusercontent.com/643417/89739636-523a1b00-da50-11ea-99b3-849a3ca73ef8.png">

**Comment by ii41** [comment]
Talking about #135, I'm thinking about whether it would be better if we expose refresh pattern to users and just allow usage of min_chars this way? If a user wants to have min_chars set to 3 they just use `...`. This will also simplify the logic much: currently we check 3 things to decided whether to start a completion: min chars, the refresh pattern, and the trigger character, and the logic is quite complicated. If the first 2 (or even all 3 of them) can be merged into simply a pattern we get better flexibility with simpler code!

**Comment by prabirshrestha** [comment]
Please try the latest master and let me know if it doesn't work.
