### ISSUE TITLE
Asyncomplete won't work with neovim and RLS (Rust Language Server)

### ISSUE THREAD

**Issue by Ronaldho80** [prabirshrestha/asyncomplete.vim#25]
* I have neovim v0.2.0. CheckHealth is ok.
* I installed asyncomplete.vim according to https://www.reddit.com/r/rust/comments/6rx634/async_autocompletion_for_vim8_and_neovim_via_rls/ (latest version using vim-Plug)
* The RLS is installed and works. I tried it with VSCode.

I have a small test project from LanguageClient-neovim. This seems to work. I get autocompletion.

With my project, it does not work (~70000 loc). I do not get completion.

**Comment by prabirshrestha** [comment]
Does LanguageClient-Neovim work on large projects? Does others like LspDefinition, LspDocumentSymbol work?

Can you try enabling log and see what is going on? Else feel free to post the log. It may contain the source code so if it is private repo feel free to remove the source contents before posting.

**Comment by Ronaldho80** [comment]
The autocompletion and the LspDefinition work with LanguageClient-Neovim, even on my big project. However, renaming does not work as well as getting the header of a function.

How can I enable the log?

**Comment by prabirshrestha** [comment]
```vim
let g:asyncomplete_log_file = expand('~/asyncomplete.log')
let g:lsp_log_file = expand('~/vim-lsp.log')
let g:lsp_log_verbose = 1
```

**Comment by keremc** [comment]
@Ronaldho80 I was able get it working by doing this:
```bash
export RUST_SRC_PATH="$(rustup run nightly rustc --print sysroot)/lib/rustlib/src/rust/src"
```
**Log file (before):** [vim-lsp.txt](https://github.com/prabirshrestha/asyncomplete.vim/files/1254000/vim-lsp.txt)
**Log file (after):** [vim-lsp.txt](https://github.com/prabirshrestha/asyncomplete.vim/files/1254004/vim-lsp.txt)

**Rust example:**
```rust
fn main() {
    let v: Vec<i8> = Vec::new();
}
```

**Comment by prabirshrestha** [comment]
Yes. You do need to correctly set the `RUST_SRC_PATH`. @keremc feel free to update this wiki and make it more explicit. https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Rust

**Comment by prabirshrestha** [comment]
Any updates on this?

**Comment by prabirshrestha** [comment]
closing due to no updates. It has worked for others too.

**Comment by steelx** [comment]
`let g:asyncomplete_auto_popup = 0` fixed for me
