### ISSUE TITLE
Strange popup layout

### ISSUE THREAD

**Issue by dubst3pp4** [prabirshrestha/asyncomplete.vim#262]
At first a big thanks for the asnycomplete and vim-lsp, which I use day to day :+1: 

I'm not sure if my problem originates from asyncomplete or is a Vim bug, so feel free to close this issue when it is not related.

I'm using gVim 8.2 Patch 1-2815 with asyncomplete with commit 6c653c3f8f1c1cf7a34522c9555d5160f36d29ee. On my system the popup with the completion preview looks strange. It seems that the content of the preview floats out of the popup window (see picture below). I don't have this issue with other popups like the one from `:LspHover` or `:LspPeekDefinition`, it is just this little popup that shows the signatures and documentation when completing a word that behaves like this.

![Bildschirmfoto von 2021-08-06 13-43-33](https://user-images.githubusercontent.com/2373731/128511801-a740c377-fa87-4ce2-a323-8d5dc1b370ce.png)

Any hints what could cause this issue?

Thanks again!

**Comment by prabirshrestha** [comment]
asyncomplete doesn't show any popups. feel free to file the issue in vim-lsp instead and we can continue the discussion there.

**Comment by dubst3pp4** [comment]
Thanks for the hint, I've now created https://github.com/prabirshrestha/vim-lsp/issues/1208 in vim-lsp.
