### ISSUE TITLE
<c-space> mapping does not work on Vim

### ISSUE THREAD

**Issue by Isopod** [prabirshrestha/asyncomplete.vim#266]
The Readme says

>### Force refresh completion
>```vim
>imap <c-space> <Plug>(asyncomplete_force_refresh)
>```

Unfortunately, this doesn't work on Vim 8.2, instead it needs to be

```vim
imap <c-@> <Plug>(asyncomplete_force_refresh)
```

It would be nice if you could add a note about this.

**Comment by prabirshrestha** [comment]
Feel red to send a PR.
