### ISSUE TITLE
Completion of buffer/workspace content

### ISSUE THREAD

**Issue by fasterius** [prabirshrestha/asyncomplete.vim#269]
Sorry if this is a stupid question, but is it possible to get autocompletion of buffer/workspace content when not using an LSP via `vim-lsp`+ `asyncomplete-lsp`? Everything works wonderfully for filetypes with supported LSPs, but for other filetypes (e.g. markdown, see https://github.com/mattn/vim-lsp-settings/issues/527) I would like to get at least autocompletion of content in the current file/buffer/workspace.

**Comment by mattn** [comment]
I still not understand what is the problem. If you are using Language Server for markdown, it should work well.
