### ISSUE TITLE
Preserve default behaviour of C-n and C-p when possible

### ISSUE THREAD

**Issue by purpleP** [prabirshrestha/asyncomplete.vim#27]
I've already opened similar issue on `deoplete` and Shougo was kind enough to implement it after I've made a pull request.
The behaviour I want to preserve is when there is not popupmenu (because there's no completion yet because you haven't entered enough characters to trigger it) `C-n` and `C-p` should insert closest next/previous word. It's actually pretty useful in some cases. Consider in python
`Some = namedtuple('|` pressing `C-p` here twice would insert `Some`. Or when passing keyword arguments in python `context=context` instead of retyping one could simply press `C-p`. Also there is a recipe that uses this behaviour to create a mapping to autoclose xml tags.

**Comment by prabirshrestha** [comment]
Could you point me to the PR from deoplete?

**Comment by purpleP** [comment]
@prabirshrestha https://github.com/Shougo/deoplete.nvim/pull/411 It may not be clear, but he hasn't merged this pull request. He have done something else to achieve the same functionality.

**Comment by roxma** [comment]
Looks like it's to restore user's `completeopt` when the plugin is not popping anything.

**Comment by purpleP** [comment]
@roxma yes, basically it is.

**Comment by prabirshrestha** [comment]
https://github.com/prabirshrestha/asyncomplete.vim/pull/69 Would this solve or do we still need that fix.
We can try fixing it in v2 branch.

**Comment by prabirshrestha** [comment]
It should had been solved by https://github.com/prabirshrestha/asyncomplete.vim/pull/69 let me know if you are still having issues.

**Comment by roxma** [comment]
FYI, ncm2 have two autocmds, `Ncm2PopupOpen` and `Ncm2PopupClose`, one can use something like this for changing completeopt when the plugin is active or inactive:

```vim
autocmd User Ncm2PopupOpen set completeopt=noinsert,menuone,noselect
autocmd User Ncm2PopupClose set completeopt=menuone
```

**Comment by prabirshrestha** [comment]
That does sound better. Will reopen it for now.

**Comment by habamax** [comment]
@purpleP Pls check #175
