### ISSUE TITLE
Auto-select the first candidate in the popup

### ISSUE THREAD

**Issue by ydzhou** [prabirshrestha/asyncomplete.vim#270]
Hi, I would like to auto select the first candidate in the popup, and when I press enter, it will be typed in. Currently I have to first press arrow-down to select the first candidate then press enter.
I do not see an option to enable this behaviour. Do you plan to support it?

**Comment by ydzhou** [comment]
Found the config.

**Comment by rohieb** [comment]
For anyone like me wondering what the solution was: setting `g:asyncomplete_auto_completeopt` and `'completeopt'`.

**Comment by alejandrohagan** [comment]
Hi!
I am looking for this? but its unclear how to apply the solution -- can you elaborate?

**Comment by rohieb** [comment]
The `g:asyncomplete_auto_completeopt` variable sets the default settings for the `'completeopt'` option, so I put this in my `~.vimrc`:

``` vim
let g:asyncomplete_auto_completeopt = "menu"
```

See https://github.com/prabirshrestha/asyncomplete.vim/blob/master/doc/asyncomplete.txt#L64 and `:help completeopt` in your vim for more information.
