### ISSUE TITLE
[Question] How  to auto popup struct field or class memer in C/C++ when you type dot or ->

### ISSUE THREAD

**Issue by tracyone** [prabirshrestha/asyncomplete.vim#277]
example

```c
struct xx_t {
int a;
int b
};

int main(){
struct xx_t var;

var. //when i type dot, nothing popup, I have to press tab or type 2 more char
}



```

**Comment by syz-lm** [comment]
C-x C-o

**Comment by tracyone** [comment]
@syz-lm YouCompletMe can auto popup complete menu when user type dot or ->

**Comment by syz-lm** [comment]
> @syz-lm YouCompletMe can auto popup complete menu when user type dot or ->

YCM is too complicated and too coupled, vim-lsp is the best I have ever used. Resolutely do not use YCM, it is big and unfriendly.

**Comment by syz-lm** [comment]
> @syz-lm YouCompletMe can auto popup complete menu when user type dot or ->

YCM is too complicated and too coupled, vim-lsp is the best I have ever used. Resolutely do not use YCM, it is big and unfriendly.

**Comment by tracyone** [comment]
@syz-lm 

I have found a way to do that

https://github.com/tracyone/vinux/commit/3d9bf3a32e1d6e3613a85e459840068c8b8ab74c

I use InsertCharPre event to detect user input  when user type dot or ">", I will change b:asyncomplete_min_chars to zero

then the complete menu will auto popup
