### ISSUE TITLE
Error going to insert mode

### ISSUE THREAD

**Issue by asarchami** [prabirshrestha/asyncomplete.vim#29]
I'm trying to install this plugin in windows (Babun) I get this error message when I go to insert mode. Am I missing any dependencies?

Error detected while processing function <SNR>59_change_tick_start:
line    6:
E117: Unknown function: timer_start
Press ENTER or type command to continue
Error detected while processing function <SNR>59_change_tick_start:
line    6:
E15: Invalid expression: timer_start(30, function('s:check_changes'), { 'repeat': -1 })

**Comment by prabirshrestha** [comment]
You need vim compiled with timers. What does `:echo has('timers')` return?

**Comment by prabirshrestha** [comment]
If you get the latest plugin it will now warn if you don't have timers enabled. https://github.com/prabirshrestha/asyncomplete.vim/commit/c8332802385877f039173cb1901578a4f0b5a909

**Comment by asarchami** [comment]
Problem was with vim version. I updated to version 8 and everything working now. Thanks
