### ISSUE TITLE
How could I set keymapping for goto function?

### ISSUE THREAD

**Issue by kepbod** [prabirshrestha/asyncomplete.vim#32]
This is great plugin. Thanks so much for your efforts. I am wondering how I could set keymapping for goto function.

**Comment by kepbod** [comment]
Sorry, this issue should be related with prabirshrestha/vim-lsp.

**Comment by prabirshrestha** [comment]
@kepbod  can you file an issue there.

**Comment by kepbod** [comment]
sure.
