### ISSUE TITLE
Better description of possible options in matches list returned by completor func

### ISSUE THREAD

**Issue by hauleth** [prabirshrestha/asyncomplete.vim#36]
README describes only use of full words while from what I have seen in docs it provides much more possibilities. I think it would be worth to list them.

**Comment by hauleth** [comment]
Ok, I found that it uses `:h complete-functions` syntax, however it would be useful to document that fact.

**Comment by prabirshrestha** [comment]
@hauleth feel free to send a PR. Docs is currently very limiting.

**Comment by hauleth** [comment]
I have seen. I would need to sit down and write you one 😉

I will try when I will have a minute to spare. For now I have written my first provider, expect PR with addition to the list. 

--
Łukasz Jan Niemier
