### ISSUE TITLE
`README.md` should note minimum NeoVim version

### ISSUE THREAD

**Issue by BatmanAoD** [prabirshrestha/asyncomplete.vim#40]
It appears that the `server_info->[...` syntax used for the RLS and `clangd` servers is not valid in NeoVim 0.1.7 (the current Debian stable version). The syntax error is hidden from the user except via the `:messages` command.

Updating to NeoVim 0.2.0, from Debian testing fixed the issue and made RLS integration work properly.

I do not see any mention of the NeoVim version requirements in the `README.md`.

**Comment by prabirshrestha** [comment]
asyncomplete doens't require lambda support it is the source or vim-lsp that needs so not sure if it is a good idea, but if that saves other people time and makes it easy I'm more than happy to add it here.

**Comment by BatmanAoD** [comment]
Okay, perhaps it would be better to put a prominent notice in the documentation for setting up the RLS and clangd sources?

**Comment by prabirshrestha** [comment]
That could be added in the wiki https://github.com/prabirshrestha/vim-lsp/wiki

But if it makes it easier to have here I’m ok with it as long as the wording is changed.

**Comment by BatmanAoD** [comment]
Okay, I think I'll just add a note that the setup for some LSP servers requires v0.2, and add that info on those specific servers to the wiki. I'll ping you when the re-wording is done, probably tomorrow.

**Comment by BatmanAoD** [comment]
@prabirshrestha I have added notes for `clangd` and `RLS` in the wiki and updated my PR.

**Comment by wsdjeg** [comment]
@prabirshrestha if I do not use vim-lsp what is the minimum version of vim for this plugin?

ref https://github.com/SpaceVim/SpaceVim/issues/1234

**Comment by BatmanAoD** [comment]
@wsdjeg This issue is about the minimum NeoVim version; the Vim version requirements are separate.

Vim 8.0 is always necessary for `asyncomplete.vim` because prior versions did not have the capability to execute tasks asynchronously.

**Comment by prabirshrestha** [comment]
Commented at https://github.com/SpaceVim/SpaceVim/issues/1234#issuecomment-355362604. This is a regression.

asycomplete.vim doesn't depend on jobs it should only depend on `timers`. But a source can depend jobs api.
