### ISSUE TITLE
Add support for clang?

### ISSUE THREAD

**Issue by wsdjeg** [prabirshrestha/asyncomplete.vim#43]
when using deoplete, I use deoplete-clang2 or deoplete-clang, will this plugin support clang sources?

**Comment by prabirshrestha** [comment]
I personally don't use c/c++ so haven't tried any of them.

1. https://github.com/keremc/asyncomplete-clang.vim
2. with language server protocol https://github.com/prabirshrestha/vim-lsp/wiki/Servers-cquery

If there are existing async clang sources let me know and it should be easy to add one. Here is a reference. https://github.com/justmao945/vim-clang/issues/111

**Comment by wsdjeg** [comment]
thank you for your info.

**Comment by prabirshrestha** [comment]
clangd lsp server wiki can be found at https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Clangd
