### ISSUE TITLE
This plugin sets completeopt?

### ISSUE THREAD

**Issue by andymass** [prabirshrestha/asyncomplete.vim#46]
Firstly, this plugin works really well and is quite lightweight.  Thank you for your work on it!  I am using it with `g:asyncomplete_auto_popup = 0` and manually invoking it with `<tab>` as described in the readme.

I am wondering why it is necessary to set `completeopt` in `s:core_complete`?  Are these settings (`menuone,noselect/noinsert`) considered mandatory for the plugin to work?  Why are they set at every invocation instead of once during initialization?  Why aren't the user's initial settings restored?

I was initially surprised when my `completeopt` settings were being changed after pressing `<tab>`.  This functionality/limitation unfortunately does not seem to be addressed in either the readme or doc.

**Comment by prabirshrestha** [comment]
It is a bug that has too be fixed. Feel free to send a PR.

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/prabirshrestha/asyncomplete.vim/pull/69
