### ISSUE TITLE
Cooperate with `jedi`

### ISSUE THREAD

**Issue by r2qokk** [prabirshrestha/asyncomplete.vim#47]
LSP does not work for me like `jedi-vim` does. In fact, it seems that it does not work, so I am trying to have `jedi` again.

1. [`jedi` is synchronous for now](https://github.com/davidhalter/jedi/issues/385), and [I have tried to follow what you have provided in synchronous example](https://github.com/prabirshrestha/asyncomplete.vim#example), but [the omnifunc that `jedi-vim` points ](https://github.com/davidhalter/jedi-vim/blob/6d05c25873f2f43225e179b30586fb6fb3c125ca/autoload/jedi.vim#L617)does not seem to work for me.  Do you have any hint?
2. From [deoplete-jedi](https://github.com/zchee/deoplete-jedi), it needs some python script to work with Neovim. How can I achieve that in `asnycomplete`?

Nice plugin. Thanks in advance :)

**Comment by prabirshrestha** [comment]
@r2qokk Try out language server protocol. https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Python
