### ISSUE TITLE
No popup appearing

### ISSUE THREAD

**Issue by bbtdev** [prabirshrestha/asyncomplete.vim#55]
Hi, 
I saw your posts on reddit and I'm really interesting in trying out your plugin. It seems the setup is different from what I'm used to or I am missing something?
No popup is showing when I type...

I'm using neovim on ubuntu:

Config
`Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-tags.vim'
let g:asyncomplete_auto_popup = 1

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"
let g:asyncomplete_log_file = expand('~/asyncomplete.log')
imap <c-space> <Plug>(asyncomplete_force_refresh)

au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#tags#get_source_options({
    \ 'name': 'tags',
    \ 'whitelist': ['c'],
    \ 'completor': function('asyncomplete#sources#tags#completor'),
    \ 'config': {
    \    'max_file_size': 50000000,
    \  },
    \ }))
`
Log:
["core","python_cm_insert_enter"]
["core","python_cm_insert_enter"]
["core","python_cm_insert_enter"]
["core","python_cm_insert_enter"]
["core","python_cm_insert_enter"]
["core", "python_cm_insert_enter"]
["core", "python_cm_insert_enter"]
["core", "python_cm_insert_enter"]
["core", "python_cm_insert_enter"]
["core", "python_cm_insert_enter"]
["core", "python_cm_insert_enter"]
["core", "python_cm_insert_enter"]
["core", "python_cm_insert_enter"]
["core", "python_cm_insert_enter"]
["core", "python_cm_insert_enter"]
["core", "python_cm_insert_enter"]

**Comment by prabirshrestha** [comment]
Is this still occurring? Which os and vim/neovim version are you using?

Also please try with a minimal vimrc

**Comment by bbtdev** [comment]
@prabirshrestha The whitelist list was wrong. Sorry! Did not encounter this type of configuration before.

**Comment by prabirshrestha** [comment]
Thanks for the update.
