### ISSUE TITLE
completion menu issue on neovim

### ISSUE THREAD

**Issue by cvlmtg** [prabirshrestha/asyncomplete.vim#58]
with the latest version of asyncomplete (which reintroduced TextChangedP) the completion is working ok, but there's a little issue: If I start typing a word the completion menu appears, but if for some reason I delete a letter (e.g. because I made a mistake) the menu disappear and it doesn't appear anymore unless I erase all the word except the first letter. It doesn't matter if I write another letter, press tab etc. If I want the menu back I have to erase the word up to the first letter. for example:

<img width="250" alt="schermata 2018-03-16 alle 20 03 09" src="https://user-images.githubusercontent.com/6401008/37539929-7e1bcc4a-2955-11e8-84e5-4111df661a3a.png">

<img width="280" alt="schermata 2018-03-16 alle 20 03 34" src="https://user-images.githubusercontent.com/6401008/37539933-8035259e-2955-11e8-8875-4341ccc8c6f2.png">

<img width="275" alt="schermata 2018-03-16 alle 20 11 17" src="https://user-images.githubusercontent.com/6401008/37540131-35f49cb6-2956-11e8-8973-5af75f08e672.png">

<img width="280" alt="schermata 2018-03-16 alle 20 11 54" src="https://user-images.githubusercontent.com/6401008/37540165-4f1e417e-2956-11e8-9231-e293ecfcbe27.png">

<img width="292" alt="schermata 2018-03-16 alle 20 03 41" src="https://user-images.githubusercontent.com/6401008/37539936-818187ee-2955-11e8-821f-09aeb179548a.png">

I'm using neovim:

```
NVIM v0.2.3-715-g1d5eec2c6
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180305-87677-1emzc9v/build/config -I/tmp/neovim-20180305-87677-1emzc9v/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/tmp/neovim-20180305-87677-1emzc9v/build/src/nvim/auto -I/tmp/neovim-20180305-87677-1emzc9v/build/include
Compilato da matteo@mecbucpro.local

Features: +acl +iconv +jemalloc +tui 
```

this is my config:

```
let g:asyncomplete_remove_duplicates = 1
let g:lsp_async_completion = 1
let g:lsp_log_file = ''

call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
      \ 'name': 'buffer',
      \ 'whitelist': ['*'],
      \ 'completor': function('asyncomplete#sources#buffer#completor'),
      \ }))

call asyncomplete#register_source(asyncomplete#sources#omni#get_source_options({
      \ 'name': 'omni',
      \ 'whitelist': ['*'],
      \ 'blacklist': ['html', 'javascript', 'javascript.jsx'],
      \ 'completor': function('asyncomplete#sources#omni#completor')
      \  }))

call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
    \ 'name': 'file',
    \ 'priority': 10,
    \ 'whitelist': ['*'],
    \ 'completor': function('asyncomplete#sources#file#completor')
    \ }))

if executable('typescript-language-server')
  call lsp#register_server({
        \ 'name': 'typescript-language-server',
        \ 'priority': 9,
        \ 'cmd': { server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
        \ 'root_uri': { server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_directory(lsp#utils#get_buffer_path(), '.git/..'))},
        \ 'whitelist': ['typescript', 'javascript', 'javascript.jsx']
        \ })
endif

inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
imap <expr> <Space> pumvisible() ? "\<C-y>\<Space>" : "\<Space>"
```

**Comment by prabirshrestha** [comment]
Could you try reverting this? 720be509c8b36de6e036a6b126f335203342c906

**Comment by cvlmtg** [comment]
it still happens

**Comment by prabirshrestha** [comment]
@cvlmtg try adding this in your vimrc. `imap <c-space> <Plug>(asyncomplete_force_refresh)`

Then press `ctrl+space` to force refresh.

**Comment by prabirshrestha** [comment]
I would also suggest you to use `au User lsp_setup call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({...})`

**Comment by cvlmtg** [comment]
Hi, I did some experiments and I see that the backspace problem is present even if I checkout v1.0, so it seems the problem might not be in the latest changes. I'll try to understand what's going on

**Comment by prabirshrestha** [comment]
The backspace problem was always there. I do plan to fix this in the future but for now you would have to use the mapping as a workaround.

**Comment by cvlmtg** [comment]
ok thanks!
