### ISSUE TITLE
Is it possible to disable dumb auto completion and only use lang server results?

### ISSUE THREAD

**Issue by kimpers** [prabirshrestha/asyncomplete.vim#60]
Hi,

Thanks for awesome plugins by the way. Your plugins are the best lang server integration I've seen. I'm getting great relevant langserver completion results but there are also "dumb" results with keywords from the current file (See `rad` in image below).
![image](https://user-images.githubusercontent.com/5450545/37878004-db315030-3062-11e8-82e1-0811dd738d45.png)

Is it possible to only use the results from the lang server?

**Comment by prabirshrestha** [comment]
Can you paste your asyncomplete source registrations?

If I register a Lang servers I usually add that language as a blacklist for buffer/syntax/omni sources.

**Comment by kimpers** [comment]
Thanks for your quick response 😃This is my full asyncomplete & vim-lsp config
```
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete-file.vim'

if executable('typescript-language-server')
    au User lsp_setup call lsp#register_server({
      \ 'name': 'typescript-language-server',
      \ 'cmd': { server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
      \ 'root_uri': { server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_directory(lsp#utils#get_buffer_path(), '.git/..'))},
      \ 'whitelist': ['typescript', 'javascript', 'javascript.jsx']
      \ })
endif

if executable('go-langserver')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'go-langserver',
        \ 'cmd': {server_info->['go-langserver', '-mode', 'stdio']},
        \ 'whitelist': ['go'],
        \ })
endif

" Path completion
au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
    \ 'name': 'file',
    \ 'whitelist': ['*'],
    \ 'priority': 10,
    \ 'completor': function('asyncomplete#sources#file#completor')
    \ }))

let g:lsp_signs_enabled = 1         " enable signs
let g:lsp_diagnostics_echo_cursor = 1 " enable echo under cursor when in normal mode

" async complete
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"
let g:asyncomplete_remove_duplicates = 1
let g:asyncomplete_smart_completion = 1
let g:asyncomplete_min_chars = 2

```

**Comment by prabirshrestha** [comment]
Is see that you are using path completion. The other completion sources are most likely coming from path. You can add the blacklist option when registering path source `'blacklist': ['typescript', 'javascript', 'javascript.jsx']`.

Can you also paste the logs? More info about it at https://github.com/prabirshrestha/vim-lsp#debugging

**Comment by kimpers** [comment]
Sorry for not getting back to you. I gave up on getting lsp to work seamlessly in vim for now
