### ISSUE TITLE
The cursor jump to some where when complete.

### ISSUE THREAD

**Issue by wsdjeg** [prabirshrestha/asyncomplete.vim#63]
@prabirshrestha Thanks for your project, and I just use this projecjt in spacevim, but sometimes I found the cursor jump to some where when complete, can you check this issue?

https://github.com/SpaceVim/SpaceVim/issues/1405

https://asciinema.org/a/LzL9RwxXGZAHP1ocSTXjNNysD

**Comment by prabirshrestha** [comment]
What source are you using?

We have seen issues where omnifunc changes cursor and we have no control over this.

https://github.com/yami-beta/asyncomplete-omni.vim/issues/4

**Comment by wsdjeg** [comment]
ok, I will try to improve the reproduce step, as this issue is reported by spacevim user, I need to make minivimrc. thanks for your reply!

**Comment by prabirshrestha** [comment]
@wsdjeg I was able to repro the cursor moving. As soon as I comment the omni source for c the cursor doesn't jump. I would suggest blacklisting omni source for c and html. Those are the ones I know that moves the cursor.

Don't think omnifunc will be solved anytime soon. Here is the discussion on vim https://github.com/vim/vim/issues/2240.

**Comment by wsdjeg** [comment]
OK，Thanks
