### ISSUE TITLE
Limiting results/completions

### ISSUE THREAD

**Issue by Bonemind** [prabirshrestha/asyncomplete.vim#64]
Hi,
First off, I'm genuinely impressed by how snappy your plugin ecosystem works, much appreciated 👍 

I couldn't find anything, so I was wondering if there is any way to limit the number of results a plugin returns (for example, at most n snippets) and/or the total number of results (e.g. at most 10 completions)?

**Comment by tuyenpm9** [comment]
`pumheight` may help?

**Comment by prabirshrestha** [comment]
When you have filtering or fuzzy search, it doesn't make sense to filter since we need to have the entire list to search. I would suggest using `pumheight`.
