### ISSUE TITLE
Cursor jumps unexpectedly when omni completion has failed.

### ISSUE THREAD

**Issue by lambdalisue** [prabirshrestha/asyncomplete.vim#70]
![cast](http://g.recordit.co/sdGNqiiere.gif)

It seems `asyncomplete-omni.vim` issue but hitting any character in insert mode at `|` move cursor at `1,1`.
It occurs when the filename is `test.vue` but `test.html`.
Btw, No message is produced.

```html
<template>
  <div>
    <span class="|">
  </div>
</template>
```

### minimal vimrc

```vim
" vim -u ~/.vim/vimrc.min
if has('vim_starting')
  set nocompatible
  execute 'set runtimepath^=~/.cache/dein/repos/github.com/prabirshrestha/async.vim'
  execute 'set runtimepath^=~/.cache/dein/repos/github.com/prabirshrestha/asyncomplete.vim'
  execute 'set runtimepath^=~/.cache/dein/repos/github.com/prabirshrestha/asyncomplete-omni.vim'
endif

au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#omni#get_source_options({
    \ 'name': 'omni',
    \ 'whitelist': ['*'],
    \ 'blacklist': ['c', 'cpp', 'html'],
    \ 'completor': function('asyncomplete#sources#omni#completor')
    \  }))

filetype plugin indent on
syntax on
```

**Comment by prabirshrestha** [comment]
Unfortunately nothing we can do here since html omni-func moves the cursor so that needs to be fixed. You could try html LSP instead.

More discussion about this can be found at https://github.com/yami-beta/asyncomplete-omni.vim/issues/4

**Comment by lambdalisue** [comment]
I don't think there is nothing we can do.

Don't you like this kind of fixes? https://github.com/yami-beta/asyncomplete-omni.vim/pull/11

**Comment by lambdalisue** [comment]
This issue has solved with above changes.

[![asciicast](https://asciinema.org/a/xd9JlliW6YbQMYrWA31EBmibk.png)](https://asciinema.org/a/xd9JlliW6YbQMYrWA31EBmibk)
