### ISSUE TITLE
Candidates disappear on backspace

### ISSUE THREAD

**Issue by tuyenpm9** [prabirshrestha/asyncomplete.vim#72]
System: gvim 8.1 - 1-116 / windows10

I'm tesing this plugin with python file, when type `p` you have a list of candidates, then type `print` --> using backspace to delete `nt`, now we have no candidates.

**Comment by prabirshrestha** [comment]
You can use `imap <c-space> <Plug>(asyncomplete_force_refresh)` mapping to enable completion to show up once it is closed.

Wasn't a simple one to fix so didn't bother to fix it yet since the workaround is simple.
