### ISSUE TITLE
Some candidates are ignored?

### ISSUE THREAD

**Issue by Shados** [prabirshrestha/asyncomplete.vim#79]
I've been attempting to wrap LanguageClient-neovim to provide completions for asyncomplete, which has mostly worked, but I've noticed that some of the candidates passed into `asyncomplete#complete()` appear to be ignored by it -- they don't show up in the popup menu, and I don't get an error message displayed or logged.

I'm unfamiliar with vimscript, so this could definitely be some error on my part, but the behaviour is pretty odd, and I can't figure out what could be causing it.

## Examples (pyls via LanguageClient-neovim providing completions)
![Image of completion for json.](https://shados.net/files/gh/asyncomplete.vim/json..png)
This first one looks about right...
![Image of completion for json.l](https://shados.net/files/gh/asyncomplete.vim/json.l.png)
Where'd `json.loads` go?
![Image of completion for json.d](https://shados.net/files/gh/asyncomplete.vim/json.d.png)
`json.dumps` has vanished but this otherwise is what I'd expect
![Image of completion for json.de](https://shados.net/files/gh/asyncomplete.vim/json.de.png)
Still good...
![Image of completion for json.c](https://shados.net/files/gh/asyncomplete.vim/json.c.png)
wat.

## minimal (tested) init.vim
```vim
call plug#begin("~/.config/nvim/plugged")
  Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': 'bash install.sh' }
  Plug 'prabirshrestha/async.vim' | Plug 'prabirshrestha/asyncomplete.vim'
call plug#end()

let g:LanguageClient_serverCommands = {}
if executable('pyls')
  let g:LanguageClient_serverCommands.python = ['pyls']
endif

" LanguageClient-neovim / asyncomplete integration wrapper, must be after LC server registrations
function! s:LanguageClient_handle_asyncomplete_callback(name, ctx, startcol, matches)
  let l:result = get(a:matches, 'result')
  let l:result = l:result is v:null ? [] : l:result

  call asyncomplete#log('LanguageClient-nvim', 'handle_asyncomplete_callback', a:matches)
  call asyncomplete#complete(a:name, a:ctx, a:startcol, l:result)
endfunction
function! s:LanguageClient_asyncompletor(opt, ctx) abort
  let l:col = a:ctx['col']
  let l:typed = a:ctx['typed']
  let l:kw = matchstr(l:typed, '\w\+$')
  let l:kwlen = len(l:kw)
  let l:startcol = l:col - l:kwlen
  " Have LC generate the completion matches and pass it a callback partial into asyncomplete
  " LanguageClient's Rust code uses 0-based column indexing instead of 1-based, AFAICT
  call LanguageClient#omniComplete(
    \ {
    \   'complete_position': (l:startcol - 1),
    \   'character': (l:col - 1),
    \ },
    \ function('s:LanguageClient_handle_asyncomplete_callback', [a:opt['name'], a:ctx, l:startcol]))
endfunction

let s:lc_languages = keys(get(g:, 'LanguageClient_serverCommands', {}))
au User asyncomplete_setup call asyncomplete#register_source({
  \ 'name': 'LanguageClient-neovim',
  \ 'whitelist': s:lc_languages,
  \ 'priority': 5,
  \ 'completor': function('s:LanguageClient_asyncompletor'),
  \ })

let g:asyncomplete_log_file = expand('~/.local/share/nvim/asyncomplete.log')
```

## asyncomplete log
Here's the [log](https://shados.net/files/gh/asyncomplete.vim/asyncomplete.log). As per the given init.vim, I added a log statement in my callback handler to capture the callback result from `LanguageClient#omniComplete()`, and from what I can see it does contain a list of valid `complete-items` in the `return` attribute. I pass that list into `asyncomplete#complete()`, but then only some of the items actually end up listed in the pop-up?

**Comment by prabirshrestha** [comment]
This is now fixed. Please try updating asyncomplete.vim
