### ISSUE TITLE
Using with FZF

### ISSUE THREAD

**Issue by djwelch** [prabirshrestha/asyncomplete.vim#80]
Hi,

Just wondering if it is possible to use this plugin with FZF, so that rather than searching using the standard prefix search, the plugin just provides a list of possible words to FZF and FZF fuzzy matches them?

**Comment by noboruma** [comment]
Looks like there is a PR for that:
https://github.com/prabirshrestha/asyncomplete.vim/pull/89

**Comment by prabirshrestha** [comment]
In v2, we will support custom filtering func allowing users to provide custom fuzzy match support. No plans to add FZF support.
