### ISSUE TITLE
g:asyncomplete_remove_duplicates doesn't work

### ISSUE THREAD

**Issue by kyouryuukunn** [prabirshrestha/asyncomplete.vim#82]
Same candidates are shown even if g:asyncomplete_remove_duplicates is 1.

For below example, Test2 and test2 were shown in both of prabirshrestha/asyncomplete-buffer.vim and prabirshrestha/asyncomplete-lsp.vim.
I used latest version asyncomplete.vim, async.vim two sources in 2018/9/17
![double](https://user-images.githubusercontent.com/1556311/45619534-9450c100-bab4-11e8-90a1-404ceac6846d.png)

**Comment by agreene-coursera** [comment]
+1 I'm also having this issue

**Comment by prabirshrestha** [comment]
Will fix this in v2 branch.

**Comment by prabirshrestha** [comment]
Please try the v2 branch. It now support custom preprocessor using `g:asyncomplete_preprocessor`.
You should now be able to do anything you want in your function. Remove duplicate is not part of the core so you will need to write a custom preprocessor.

https://github.com/prabirshrestha/asyncomplete.vim/blob/1eacfe20b68d48f0168b83b3df0e008054a15ba3/doc/asyncomplete.txt#L55-L86

**Comment by zoumi** [comment]
Combine this with sources' priority?

**Comment by zoumi** [comment]
```
function! s:my_asyncomplete_preprocessor(options, matches) abort 
    let l:dict = {} 
    for [l:source_name, l:matches] in items(a:matches) 
        let l:source_priority = get(asyncomplete#get_source_info(l:source_name),'priority',0)
        for l:item in l:matches['items'] 
            if stridx(l:item['word'], a:options['base']) == 0
            "if l:item['word'] =~ '^' . a:options['base'] 
                let l:item['priority'] = l:source_priority
                if has_key(l:dict,l:item['word'])
                    let l:old_item = get(l:dict, l:item['word'])
                    if l:old_item['priority'] <  l:source_priority
                        let l:dict[item['word']] = l:item
                    endif
                else
                    let l:dict[item['word']] = l:item
                endif
            endif 
        endfor 
    endfor 
    let l:items =  sort(values(l:dict),{a, b -> b['priority'] - a['priority']})
    call asyncomplete#preprocess_complete(a:options, l:items) 
endfunction 

let g:asyncomplete_preprocessor = [function('s:my_asyncomplete_preprocessor')]

```
