### ISSUE TITLE
Completion menu doesn't close upon <Cr> with smart completion enabled

### ISSUE THREAD

**Issue by p0deje** [prabirshrestha/asyncomplete.vim#85]
First of all, thank you for an amazing completion plugin, it's truly awesome!

I have a small issue after upgrading and enabling smart completion. Without smart completion enabled, when completion menu popups, you don't select any item and press `<Cr>` - it would close the completion menu. However, with smart completion enabled, after you press `<Cr>` it just reopens completion menu, so you need to manually close it some other way (e.g. press `<Esc>`).

My vimrc:

```viml
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'
Plug 'prabirshrestha/asyncomplete-file.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim' " depends: vim-lsp
Plug 'prabirshrestha/vim-lsp' " depends: async.vim

let g:asyncomplete_remove_duplicates = 1
let g:asyncomplete_smart_completion = 1

function! asyncomplete_sources() abort
  call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
        \ 'name': 'buffer',
        \ 'whitelist': ['*'],
        \ 'completor': function('asyncomplete#sources#buffer#completor'),
        \ }))
  call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
        \ 'name': 'file',
        \ 'whitelist': ['*'],
        \ 'completor': function('asyncomplete#sources#file#completor')
        \ }))
endfunction

autocmd User asyncomplete_setup call asyncomplete_sources()

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
```

**Comment by prabirshrestha** [comment]
Can you try if you see this bug in v2 branch? Still at an early phase of v2.

Smart completion doesn't exist in v2 yet. Instead we will have a feature to allow custom filtering function.

**Comment by prabirshrestha** [comment]
There is now a new `asyncomplet#cancel_popup` and asyncomplete#close_popup` apis. You can refer to the solutions at https://github.com/prabirshrestha/asyncomplete.vim/issues/117

**Comment by p0deje** [comment]
Thank you!
