### ISSUE TITLE
Problems between lsp_async_completion and asyncomplete-ultisnips

### ISSUE THREAD

**Issue by entropitor** [prabirshrestha/asyncomplete.vim#88]
When I set vim-lsp's `lsp_async_completion=1`, my Ultisnips completion just flashes for a short amount of time and is then gone again, if I force refresh, it doesn't show any Ultisnips completion results.

When I set `lsp_async_completion=0`, I get duplicate results (even though I have that flag for duplicate results enabled, it's not filtering them out)

Let me know if I should repost this issue in another repository!

**Comment by prabirshrestha** [comment]
Could you try v2 branch?

**Comment by prabirshrestha** [comment]
Please try the latest master. I just merged v2 branch.
