### ISSUE TITLE
Deduplicate completion items

### ISSUE THREAD

**Issue by andreypopp** [prabirshrestha/asyncomplete.vim#9]
Currently when more than a single sources is enabled for a buffer it is possible to get duplicates in the completion menu. For example, for JS I use both `buffer` and `flow` (this is needed as `buffer` is more robust — even when syntax is not valid it can do its job while `flow` is more "correct").

I think `asyncomplete` can do dedup. That would probably require to provide some priority order for sources though — for example `flow` should be prioritised over `buffer` as its completions are more "correct" (based on semantic source code knowledge).

**Comment by prabirshrestha** [comment]
This should be easy to implement. Need to update `s:python_refresh_completions`. 

Here is the pseudo code.

```vim
for [l:name, l:info] in sort_by_priority(items(s:matches))
```

**Comment by renstrom** [comment]
Hmm, I'm bad a Vim script, so this is probably inefficient. But wouldn't this work? Seems to do the trick when I tried it for a minute.

```diff
diff --git a/autoload/asyncomplete.vim b/autoload/asyncomplete.vim
index b102471..3fa7e6c 100644
--- a/autoload/asyncomplete.vim
+++ b/autoload/asyncomplete.vim
@@ -326,6 +326,7 @@ function! s:python_refresh_completions(ctx) abort
 
     let l:filtered_matches = []
 
+    let l:matches = filter(copy(l:matches), 'index(l:matches, v:val, v:key+1)==-1')
     let l:sources = sort(keys(s:matches), function('s:sort_sources_by_priority'))
 
     for l:name in l:sources
```

Mostly stolen from https://stackoverflow.com/a/6630950/1862923

**Comment by prabirshrestha** [comment]
@renstrom it works but could slow down if you have lot of items. If we put this behind a flag I'm ok with it. Feel free to send a PR.

Out of curiosity what language are you using? I mainly use typescript and I disable all buffer, syntax and omni sources when in Typescript. If I don't have a proper language server I use omni, followed by syntax and then buffer.

**Comment by renstrom** [comment]
>Feel free to send a PR.

I'll see what I can do.

>Out of curiosity what language are you using? 

Well mainly Python. But also a bunch of other languages every now and then like C/C++, Markdown, YAML, Go, Rust, Bash, Javascript, etc. But now that you mention it, I could certainly improve my white- and blacklists for my sources! I still think dedupe is a worthy feature though, especially coupled with priority (just noticed a bug in the diff, the dedupe should happen _after_ sorting).
