### ISSUE TITLE
Keyword completion as source

### ISSUE THREAD

**Issue by mogenson** [prabirshrestha/asyncomplete.vim#93]
Awesome plugin!

Do you have a suggestion of how to include regular keyword completions as a source?

When writing a regular text document it's nice to be able to `set complete+=kspell` and get dictionary word suggestions from pressing `<C-n>` or `<C-p>`.

**Comment by zoumi** [comment]
I foud  'vim-scripts/AutoComplPop' can work with asyncomplete.vim
