### ISSUE TITLE
Autocompletion won't work automatically

### ISSUE THREAD

**Issue by jokem59** [prabirshrestha/asyncomplete.vim#94]
Hi All,

I'm trying to check out asyncomplete and there's a mismatch between my expectations and results.  My expectation is that as I type, I should see suggestions start popping up.  But in reality, after I type something (while still in Insert mode), I press <Ctrl-N> and I see a list pop up where I can tab through some results.  This is in the context of a simple C++ project.  I'm using vim8.1 in Windows and I'm using Pathogen to handle all the extra additions listed here:

[asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim)
[async.vim](https://github.com/prabirshrestha/async.vim)
[vim-lsp](https://github.com/prabirshrestha/vim-lsp)

I've verified that I've downloaded the LLVM binaries and I've registered with the clangd LSP.  Here's a snippet from my .vimrc.

```
" Registering clangd LSP with asyncomplete
if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
        \ })
endif

" Asyncomplete tab completion
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<CR>"
let g:asyncomplete_remove_duplicates = 1
let g:asyncomplete_smart_completion = 1
```

Any ideas on the disconnect between my expectation and my current result??

**Comment by prabirshrestha** [comment]
Seems like you don't have `let g:asyncomplete_auto_popup = 1`.

**Comment by jokem59** [comment]
Hi @prabirshrestha , thanks for the reply.  According to the documentation, I was under the impression that this option was ON by default: "By default asyncomplete will automatically show the autocomplete popup menu as you start typing."

I manually added `let g:asyncomplete_auto_popup = 1` and opened up my C++ project and I'm not seeing the auto popup.

Is there something else I could be missing?  Is there any other information I can provide that would help troubleshoot this information?

**Comment by prabirshrestha** [comment]
Please provide logs for both asyncomplete and lsp. Also suggest trying other lsp servers to see if it work. Refer to vim-lsp wiki on how to setup sources

**Comment by jokem59** [comment]
[vim-lsp.log](https://github.com/prabirshrestha/asyncomplete.vim/files/2709594/vim-lsp.log)
[asyncomplete.log](https://github.com/prabirshrestha/asyncomplete.vim/files/2709595/asyncomplete.log)

I don't see too much going on in the logs, could that be indicative of something?  I tried setting up rust according to the vim-lsp wiki with no luck as well.

**Comment by jsit** [comment]
You shouldn't need `async.vim`.

You also need to add asyncomplete sources, such as [omni](https://github.com/yami-beta/asyncomplete-omni.vim) or [tags](https://github.com/prabirshrestha/asyncomplete-tags.vim).

After installing the source plugins, you'll also need to "register" them in your `.vimrc`, as shown in their individual READMEs, e.g. for omni:

```
call asyncomplete#register_source(asyncomplete#sources#omni#get_source_options({
  \ 'name': 'omni',
  \ 'whitelist': ['*'],
  \ 'blacklist': ['c', 'cpp', 'html'],
  \ 'completor': function('asyncomplete#sources#omni#completor')
\  }))
```

**Comment by prabirshrestha** [comment]
Please give v2 branch a try and let me know if you are still hitting the issue. Currently it does auto popup automatically. I do plan to add a flag to disable autopopup.

**Comment by jsit** [comment]
Do I need to do anything special to get V2 working? No autocomplete menu is appearing for me.

**Comment by prabirshrestha** [comment]
Make sure to get the latest and switch to v2 branch.

Currently I have only been testing vim-lsp and https://github.com/prabirshrestha/asyncomplete-necovim.vim and dogfooding asyncomplete v2.

**Comment by jsit** [comment]
I don't have vim-lsp set up; just asyncomplete-buffer. I have the latest v2 and it's not working with that.

My minimal `.vimrc`:

```vim
set nocompatible
set runtimepath=~/.vim/bundle/asyncomplete.vim,~/.vim/bundle/asyncomplete-buffer.vim,$VIMRUNTIME
filetype plugin on
filetype indent on
syntax on
autocmd BufEnter * call asyncomplete#enable_for_buffer()
au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
	\ 'name': 'buffer',
	\ 'whitelist': ['*'],
	\ 'blacklist': ['go','vim'],
	\ 'completor': function('asyncomplete#sources#buffer#completor'),
	\ }))
```

**Comment by prabirshrestha** [comment]
Buffer doesn’t work yet because I haven’t implement events yet. Try ominfunc source.

**Comment by prabirshrestha** [comment]
@jsit Pushed the fix for event support so buffer sources should work on. Please update to latest v2 and try again. current v2 branch now has most of the core features of v1. Feel free to send PRs to v2 branch.

**Comment by jsit** [comment]
Getting this error:

```
Error detected while processing function <SNR>21_recompute_pum[38]..<SNR>21_default_filter:
line    3:
E714: List required
```

`.vimrc`:

```vim
set nocompatible
set runtimepath=~/.vim/bundle/asyncomplete.vim,~/.vim/bundle/asyncomplete-omni.vim,~/.vim/bundle/asyncomplete-buffer.vim,$VIMRUNTIME
filetype plugin on
filetype indent on
syntax on
autocmd BufEnter * call asyncomplete#enable_for_buffer()
au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
	\ 'name': 'buffer',
	\ 'whitelist': ['*'],
	\ 'blacklist': ['go','vim'],
	\ 'completor': function('asyncomplete#sources#buffer#completor'),
	\ }))
au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#omni#get_source_options({
	\ 'name': 'omni',
	\ 'whitelist': ['*'],
	\ 'blacklist': ['c', 'cpp', 'html'],
	\ 'completor': function('asyncomplete#sources#omni#completor')
	\  }))
```

**Comment by prabirshrestha** [comment]
Could you try adding some logs in `function! s:default_filter(options) abort`. I can't repro the error.
I'm wondering if `l:matches['items']` doesn't exist.

**Comment by prabirshrestha** [comment]
@jsit Can you try pulling the latest code. The bug was in `s:normalize_items` which is now fixed.

**Comment by prabirshrestha** [comment]
Please try v2 branch.
