### ISSUE TITLE
Autocomplete ignores `textEdit` and `additionalTextEdit` fields. Uses `label` only

### ISSUE THREAD

**Issue by kaushik-work** [prabirshrestha/asyncomplete.vim#99]
The LSP allow us to send an autocomplete with `textEdit` and `additionalTextEdits` fields. This client seems to ignore those fields and use only the label for autocompletion.

**Comment by prabirshrestha** [comment]
Not a bug in asyncomplete.vim. Please file bugs in vim-lsp if it is still the case. There were fixes done in vimlsp on text edits recently.
